### ISSUE TITLE
System.IO.DirectoryNotFoundException: Could not find a part of the path '/opt/dotnet'

### ISSUE THREAD

**Issue by dennis-yemelyanov** [microsoft/Oryx#1190]
### Bug Report

When trying to use Azure App Service deployment for .NET 5 project I'm getting this error in /tmp/build-debug.log:

```
2021-12-27 03:28:16.4149|ERROR|Microsoft.Oryx.BuildScriptGeneratorCli.CommandBase|Exception caughtSystem.IO.DirectoryNotFoundException: Could not find a part of the path '/opt/dotnet'.
   at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
   at System.IO.Enumeration.FileSystemEnumerator`1.Init()
   at System.IO.Enumeration.FileSystemEnumerator`1..ctor(String directory, Boolean isNormalized, EnumerationOptions options)
   at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, EnumerationOptions options, Boolean isNormalized)
   at System.IO.Enumeration.FileSystemEnumerableFactory.UserDirectories(String directory, String expression, EnumerationOptions options)
   at System.IO.Directory.InternalEnumeratePaths(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
   at System.IO.Directory.GetDirectories(String path)
   at Microsoft.Oryx.BuildScriptGenerator.DotNetCore.DotNetCoreOnDiskVersionProvider.GetSupportedVersions() in C:\A\1\8\s\src\BuildScriptGenerator\DotNetCore\VersionProviders\DotNetCoreOnDiskVersionProvider.cs:line 35
   at Microsoft.Oryx.BuildScriptGenerator.DotNetCore.DotNetCoreVersionProvider.GetSupportedVersions() in C:\A\1\8\s\src\BuildScriptGenerator\DotNetCore\VersionProviders\DotNetCoreVersionProvider.cs:line 51
   at Microsoft.Oryx.BuildScriptGenerator.DotNetCore.DotNetCorePlatform.GetMaxSatisfyingRuntimeVersionAndVerify(String runtimeVersion) in C:\A\1\8\s\src\BuildScriptGenerator\DotNetCore\DotnetCorePlatform.cs:line 356
   at Microsoft.Oryx.BuildScriptGenerator.DotNetCore.DotNetCorePlatform.ResolveVersions(RepositoryContext context, PlatformDetectorResult detectorResult) in C:\A\1\8\s\src\BuildScriptGenerator\DotNetCore\DotnetCorePlatform.cs:line 263
   at Microsoft.Oryx.BuildScriptGenerator.DotNetCore.DotNetCorePlatform.Detect(RepositoryContext context) in C:\A\1\8\s\src\BuildScriptGenerator\DotNetCore\DotnetCorePlatform.cs:line 95
   at Microsoft.Oryx.BuildScriptGenerator.DefaultPlatformsInformationProvider.GetPlatformsInfo(RepositoryContext context) in C:\A\1\8\s\src\BuildScriptGenerator\DefaultPlatformsInformationProvider.cs:line 53
   at Microsoft.Oryx.BuildScriptGenerator.DefaultBuildScriptGenerator.GenerateBashScript(BuildScriptGeneratorContext context, String& script, List`1 checkerMessageSink) in C:\A\1\8\s\src\BuildScriptGenerator\DefaultBuildScriptGenerator.cs:line 69
   at Microsoft.Oryx.BuildScriptGeneratorCli.BuildScriptGenerator.TryGenerateScript(String& generatedScript, Exception& exception) in C:\A\1\8\s\src\BuildScriptGeneratorCLI\BuildScriptGenerator.cs:line 65
   at Microsoft.Oryx.BuildScriptGeneratorCli.BuildCommand.Execute(IServiceProvider serviceProvider, IConsole console) in C:\A\1\8\s\src\BuildScriptGeneratorCLI\Commands\BuildCommand.cs:line 166
   at Microsoft.Oryx.BuildScriptGeneratorCli.CommandBase.OnExecute(CommandLineApplication app, IConsole console) in C:\A\1\8\s\src\BuildScriptGeneratorCLI\Commands\CommandBase.cs:line 83
```
What is /opt/dotnet and who is supposed to provide it?

Any workarounds?

**Comment by qianz2** [comment]
@dennis-yemelyanov , could you let us know what command you were running? '/opt/dotnet' is a directory where oryx stored dotnet SDKs, it's default in an oryx image. Have you accidentally removed the directory by any chance?

**Comment by simonjj** [comment]
We're closing this issue due to its age. If this is still impacting you please open a new issue and simply link back to this one.
