### ISSUE TITLE
Exception ArgumentOutOfRange when building basic php8.0 app in Azure

### ISSUE THREAD

**Issue by FrediL** [microsoft/Oryx#1626]
### Bug Report

I'm trying to deploy basic php app with composer and symfony in WebApp on linux. I integrated with bitbucket for CI, but builds fails on oryx trying to build application. 

```
Oryx Version: 0.2.20220812.1, Commit: cdf6b1bef165d05b94830e963646495967d938f4, ReleaseTagName: 20220812.1
```

```
2022-10-24 14:38:38.9542|INFO|Microsoft.Oryx.BuildScriptGeneratorCli.CommandBase|Oryx command line: /opt/buildscriptgen/GenerateBuildScript.dll build /home/site/repository -o /home/site/wwwroot --platform php --platform-version 8.0 -p virtualenv_name= --log-file /tmp/build-debug.log -i /tmp/8dab5cd6f94262e
2022-10-24 14:38:39.2481|DEBUG|Microsoft.Oryx.BuildScriptGenerator.DefaultBuildScriptGenerator|Available checkers: 5
2022-10-24 14:38:39.3089|DEBUG|Microsoft.Oryx.Detector.Node.NodeDetector|Could not find package.json/package-lock.json/yarn.lock in repo
2022-10-24 14:38:39.3201|DEBUG|Microsoft.Oryx.Detector.Node.NodeDetector|Could not find typical Node.js files in repo
2022-10-24 14:38:39.3201|DEBUG|Microsoft.Oryx.Detector.Node.NodeDetector|App in repo is not a NodeJS app
2022-10-24 14:38:39.5601|ERROR|Microsoft.Oryx.BuildScriptGeneratorCli.CommandBase|Exception caughtSystem.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at Microsoft.Oryx.Detector.ParserHelper.ParseYamlFile(ISourceRepo sourceRepo, String filePath) in /usr/oryx/src/Detector/ParserHelper.cs:line 75
   at Microsoft.Oryx.Detector.Hugo.HugoDetector.IsHugoYamlFile(ISourceRepo sourceRepo, String[] subPaths) in /usr/oryx/src/Detector/Hugo/HugoDetector.cs:line 188
   at Microsoft.Oryx.Detector.Hugo.HugoDetector.IsHugoApp(ISourceRepo sourceRepo, String& appDirectory) in /usr/oryx/src/Detector/Hugo/HugoDetector.cs:line 120
   at Microsoft.Oryx.Detector.Hugo.HugoDetector.Detect(DetectorContext context) in /usr/oryx/src/Detector/Hugo/HugoDetector.cs:line 49
   at Microsoft.Oryx.BuildScriptGenerator.Hugo.HugoPlatform.Detect(RepositoryContext context) in /usr/oryx/src/BuildScriptGenerator/Hugo/HugoPlatform.cs:line 57
   at Microsoft.Oryx.BuildScriptGenerator.DefaultPlatformsInformationProvider.GetPlatformsInfo(RepositoryContext context) in /usr/oryx/src/BuildScriptGenerator/DefaultPlatformsInformationProvider.cs:line 53
   at Microsoft.Oryx.BuildScriptGenerator.DefaultBuildScriptGenerator.GenerateBashScript(BuildScriptGeneratorContext context, String& script, List`1 checkerMessageSink) in /usr/oryx/src/BuildScriptGenerator/DefaultBuildScriptGenerator.cs:line 70
   at Microsoft.Oryx.BuildScriptGeneratorCli.BuildScriptGenerator.TryGenerateScript(String& generatedScript, Exception& exception) in /usr/oryx/src/BuildScriptGeneratorCli/BuildScriptGenerator.cs:line 65
   at Microsoft.Oryx.BuildScriptGeneratorCli.BuildCommand.Execute(IServiceProvider serviceProvider, IConsole console) in /usr/oryx/src/BuildScriptGeneratorCli/Commands/BuildCommand.cs:line 166
   at Microsoft.Oryx.BuildScriptGeneratorCli.CommandBase.OnExecute(CommandLineApplication app, IConsole console) in /usr/oryx/src/BuildScriptGeneratorCli/Commands/CommandBase.cs:line 84
```

**Comment by pauld-msft** [comment]
Hi @FrediL , thanks for submitting this issue. Do you have a public repository or reproduction steps that we could use to help debug this issue?

**Comment by pauld-msft** [comment]
Hi @FrediL  I've opened a pull request that will hopefully keep this issue from happening again, but without a repository where you are seeing the issue, it is difficult to confirm that this will fix your problem

**Comment by pauld-msft** [comment]
@FrediL , would you be able to confirm for us that you have an empty `config.yaml` in your hugo repo, where the oryx build is being executed? This is the case where we believe the issue will present itself

**Comment by pauld-msft** [comment]
PR is merged, closing.
