### ISSUE TITLE
Symfony PHP 8 Linux deployment, same code working from Github but not for Azure Devops

### ISSUE THREAD

**Issue by wuangyalin** [microsoft/Oryx#1682]
Hi,

We are recently upgrading our PHP apps hosted on Azure web apps, in order to upgrade to PHP8, we have to change the server from Windows to Linux environment. However, it seems there are some issues to deploy Symfony based code from Azure Devops via the Web App Deployment Center.

How to reproduce the issue: sorry my organization doesn't allow me to create a public repo and this issue just happen on Azure Devops, so you have to setup the repo by yourself.

1. Create a project in git project in Azure Devops. 
2. Run `composer create-project symfony/skeleton:"^5.4" my_project_directory` (yes, even the standard Symfony code doesn't work)
3. Push the symfony base code to Azure Devops repo.
4. On Azure Web App Deployment Center, connect this repo and click save.
5. Then I'm getting the below error:
```
Command: oryx build /home/site/repository -o /home/site/wwwroot --platform php --platform-version 8.1 -p virtualenv_name= --log-file /tmp/build-debug.log  -i /tmp/8dac6b55f334287 | tee /tmp/oryx-build.log
Operation performed by Microsoft Oryx, https://github.com/Microsoft/Oryx
You can report issues at https://github.com/Microsoft/Oryx/issues

Oryx Version: 0.2.20220825.1, Commit: 24032445dbf7bf6ef068688f1b123a7144453b7f, ReleaseTagName: 20220825.1

Build Operation ID: |3cJo5vIXJHc=.a5116173_
Repository Commit : 447ac2dd2fe45f096dadf79d0ef078827b555ae3

Detecting platforms...
Error: Oops... An unexpected error has occurred.
Error: System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at Microsoft.Oryx.Detector.ParserHelper.ParseYamlFile(ISourceRepo sourceRepo, String filePath) in /usr/oryx/src/Detector/ParserHelper.cs:line 75
   at Microsoft.Oryx.Detector.Hugo.HugoDetector.IsHugoYamlFile(ISourceRepo sourceRepo, String[] subPaths) in /usr/oryx/src/Detector/Hugo/HugoDetector.cs:line 188
   at Microsoft.Oryx.Detector.Hugo.HugoDetector.IsHugoApp(ISourceRepo sourceRepo, String& appDirectory) in /usr/oryx/src/Detector/Hugo/HugoDetector.cs:line 120
   at Microsoft.Oryx.Detector.Hugo.HugoDetector.Detect(DetectorContext context) in /usr/oryx/src/Detector/Hugo/HugoDetector.cs:line 49
   at Microsoft.Oryx.BuildScriptGenerator.Hugo.HugoPlatform.Detect(RepositoryContext context) in /usr/oryx/src/BuildScriptGenerator/Hugo/HugoPlatform.cs:line 57
   at Microsoft.Oryx.BuildScriptGenerator.DefaultPlatformsInformationProvider.GetPlatformsInfo(RepositoryContext context) in /usr/oryx/src/BuildScriptGenerator/DefaultPlatformsInformationProvider.cs:line 53
   at Microsoft.Oryx.BuildScriptGenerator.DefaultBuildScriptGenerator.GenerateBashScript(BuildScriptGeneratorContext context, String& script, List`1 checkerMessageSink) in /usr/oryx/src/BuildScriptGenerator/DefaultBuildScriptGenerator.cs:line 70
   at Microsoft.Oryx.BuildScriptGeneratorCli.BuildScriptGenerator.TryGenerateScript(String& generatedScript, Exception& exception) in /usr/oryx/src/BuildScriptGeneratorCli/BuildScriptGenerator.cs:line 65
   at Microsoft.Oryx.BuildScriptGeneratorCli.BuildCommand.Execute(IServiceProvider serviceProvider, IConsole console) in /usr/oryx/src/BuildScriptGeneratorCli/Commands/BuildCommand.cs:line 168
   at Microsoft.Oryx.BuildScriptGeneratorCli.CommandBase.OnExecute(CommandLineApplication app, IConsole console) in /usr/oryx/src/BuildScriptGeneratorCli/Commands/CommandBase.cs:line 84
Error: Oops... An unexpected error has occurred.\nError: System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')\n   at System.Collections.Generic.List`1.get_Item(Int32 index)\n   at Microsoft.Oryx.Detector.ParserHelper.ParseYamlFile(ISourceRepo sourceRepo, String filePath) in /usr/oryx/src/Detector/ParserHelper.cs:line 75\n   at Microsoft.Oryx.Detector.Hugo.HugoDetector.IsHugoYamlFile(ISourceRepo sourceRepo, String[] subPaths) in /usr/oryx/src/Detector/Hugo/HugoDetector.cs:line 188\n   at Microsoft.Oryx.Detector.Hugo.HugoDetector.IsHugoApp(ISourceRepo sourceRepo, String& appDirectory) in /usr/oryx/src/Detector/Hugo/HugoDetector.cs:line 120\n   at Microsoft.Oryx.Detector.Hugo.HugoDetector.Detect(DetectorContext context) in /usr/oryx/src/Detector/Hugo/HugoDetector.cs:line 49\n   at Microsoft.Oryx.BuildScriptGenerator.Hugo.HugoPlatform.Detect(RepositoryContext context) in /usr/oryx/src/BuildScriptGenerator/Hugo/HugoPlatform.cs:line 57\n   at Microsoft.Oryx.BuildScriptGenerator.DefaultPlatformsInformationProvider.GetPlatformsInfo(RepositoryContext context) in /usr/oryx/src/BuildScriptGenerator/DefaultPlatformsInformationProvider.cs:line 53\n   at Microsoft.Oryx.BuildScriptGenerator.DefaultBuildScriptGenerator.GenerateBashScript(BuildScriptGeneratorContext context, String& script, List`1 checkerMessageSink) in /usr/oryx/src/BuildScriptGenerator/DefaultBuildScriptGenerator.cs:line 70\n   at Microsoft.Oryx.BuildScriptGeneratorCli.BuildScriptGenerator.TryGenerateScript(String& generatedScript, Exception& exception) in /usr/oryx/src/BuildScriptGeneratorCli/BuildScriptGenerator.cs:line 65\n   at Microsoft.Oryx.BuildScriptGeneratorCli.BuildCommand.Execute(IServiceProvider serviceProvider, IConsole console) in /usr/oryx/src/BuildScriptGeneratorCli/Commands/BuildCommand.cs:line 168\n   at Microsoft.Oryx.BuildScriptGeneratorCli.CommandBase.OnExecute(CommandLineApplication app, IConsole console) in /usr/oryx/src/BuildScriptGeneratorCli/Commands/CommandBase.cs:line 84\n/bin/bash -c "oryx build /home/site/repository -o /home/site/wwwroot --platform php --platform-version 8.1 -p virtualenv_name= --log-file /tmp/build-debug.log  -i /tmp/8dac6b55f334287 | tee /tmp/oryx-build.log ; exit $PIPESTATUS "
```

I also created a Github repo with the exactly same process, and it is working. 

Can you please help me to resolve this issue? My company is using Azure Devops so it is not possible to move them into Github.

Thanks in advance.

**Comment by pauld-msft** [comment]
Hello @wuangyalin , this looks quite similar to https://github.com/microsoft/Oryx/issues/1626 . The fix we merged for that previous issue should keep us from running into the issue once it rolls out, however that could take some time.

Perhaps you will be able to help us understand why we are seeing this issue. Are there any empty `.yaml` files in your repository?

**Comment by wuangyalin** [comment]
> Hello @wuangyalin , this looks quite similar to #1626 . The fix we merged for that previous issue should keep us from running into the issue once it rolls out, however that could take some time.
> 
> Perhaps you will be able to help us understand why we are seeing this issue. Are there any empty `.yaml` files in your repository?

Hi @pauld-msft , yes there are some empty yaml files in the repo, when I delete/add something into the files the CI works now.

Thanks for you quick response.

**Comment by pauld-msft** [comment]
You're welcome. Closing issue as fix has been merged.
