### ISSUE TITLE
Cannot reach Oryx via Proxy for remote build

### ISSUE THREAD

**Issue by abhendu123** [microsoft/Oryx#1958]
Hi Team,

We have build an enterprise platform where in we are reaching to the pre-requisite sites ( as mentioned below ) of function via proxy - 

1. oryx-cdn.microsoft.io (build system which automatically compiles source code repos into runnable artifacts.)
2. pypi.org (Python Package Index (PyPI) which is a repository of software packages)
3. files.pythonhosted.org  (pip install for packages on the Python Package Index)

In the url ( https://github.com/microsoft/Oryx/blob/main/doc/hosts/appservice.md  ) - under, "Network Dependencies", it is mentioned that - 

"When using App Service with a Virtual Network or an App Service Environment, you will need to allow outbound access from the webapp to oryx-cdn.microsoft.io on port 443. oryx-cdn.microsoft.io hosts the Oryx packages corresponding to each SDK language and version. If this network dependency is blocked, then App Service will not be able to build your application using Oryx."

But we need to reach "oryx-cdn.microsoft.io" from remote docker container via proxy and we are unable to do so.
It is showing us the following error message while we are trying to build a job remotely - 

```
(.venv) D:\demo_func_app\demo-app-func>func azure functionapp publish des-dev-uks-func-os-lz-001 --build remote      
Getting site publishing info...
Creating archive for current directory...
Performing remote build for functions project.
Deleting the old .python_packages directory
Uploading 2.03 KB [###############################################################################]
Remote build in progress, please wait...
Updating submodules.
Preparing deployment for commit id 'fd2c0168-2'.
PreDeployment: context.CleanOutputPath False
PreDeployment: context.OutputPath /home/site/wwwroot
Repository path is /tmp/zipdeploy/extracted
Running oryx build...
Command: oryx build /tmp/zipdeploy/extracted -o /tmp/build/expressbuild --platform python --platform-version 3.10.4 -i /tmp/8db40c6ac818225 -p packagedir=.python_packages/lib/site-packages
Operation performed by Microsoft Oryx, https://github.com/Microsoft/Oryx
You can report issues at https://github.com/Microsoft/Oryx/issues
Oryx Version: 0.2.20220825.1, Commit: 24032445dbf7bf6ef068688f1b123a7144453b7f, ReleaseTagName: 20220825.1
Build Operation ID: |u3FWCpBsIFY=.5b7e82ec_
Repository Commit : fd2c0168-2080-4a4b-b32d-3dc6993f2a0f
Detecting platforms...
Error: Oops... An unexpected error has occurred.
Error: System.AggregateException: One or more errors occurred. (A task was canceled.)
 ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Microsoft.Oryx.BuildScriptGenerator.SdkStorageVersionProviderBase.GetAvailableVersionsFromStorage(String platformName) in /usr/oryx/src/BuildScriptGenerator/SdkStorageVersionProviderBase.cs:line 51
   at Microsoft.Oryx.BuildScriptGenerator.Python.PythonSdkStorageVersionProvider.GetVersionInfo() in /usr/oryx/src/BuildScriptGenerator/Python/VersionProviders/PythonSdkStorageVersionProvider.cs:line 25
   at Microsoft.Oryx.BuildScriptGenerator.Python.PythonVersionProvider.GetVersionInfo() in /usr/oryx/src/BuildScriptGenerator/Python/VersionProviders/PythonVersionProvider.cs:line 44
   at Microsoft.Oryx.BuildScriptGenerator.Python.PythonPlatform.get_SupportedVersions() in /usr/oryx/src/BuildScriptGenerator/Python/PythonPlatform.cs:line 117
   at Microsoft.Oryx.BuildScriptGenerator.Python.PythonPlatform.GetMaxSatisfyingVersionAndVerify(String version) in /usr/oryx/src/BuildScriptGenerator/Python/PythonPlatform.cs:line 624
   at Microsoft.Oryx.BuildScriptGenerator.Python.PythonPlatform.ResolveVersions(RepositoryContext context, PlatformDetectorResult 
detectorResult) in /usr/oryx/src/BuildScriptGenerator/Python/PythonPlatform.cs:line 387
   at Microsoft.Oryx.BuildScriptGenerator.Python.PythonPlatform.Detect(RepositoryContext context) in /usr/oryx/src/BuildScriptGenerator/Python/PythonPlatform.cs:line 136
   at Microsoft.Oryx.BuildScriptGenerator.DefaultPlatformsInformationProvider.GetPlatformsInfo(RepositoryContext context) in /usr/oryx/src/BuildScriptGenerator/DefaultPlatformsInformationProvider.cs:line 53
   at Microsoft.Oryx.BuildScriptGenerator.DefaultBuildScriptGenerator.GenerateBashScript(BuildScriptGeneratorContext context, String& script, List`1 checkerMessageSink) in /usr/oryx/src/BuildScriptGenerator/DefaultBuildScriptGenerator.cs:line 70
   at Microsoft.Oryx.BuildScriptGeneratorCli.BuildScriptGenerator.TryGenerateScript(String& generatedScript, Exception& exception) in /usr/oryx/src/BuildScriptGeneratorCli/BuildScriptGenerator.cs:line 65
   at Microsoft.Oryx.BuildScriptGeneratorCli.BuildCommand.Execute(IServiceProvider serviceProvider, IConsole console) in /usr/oryx/src/BuildScriptGeneratorCli/Commands/BuildCommand.cs:line 168
   at Microsoft.Oryx.BuildScriptGeneratorCli.CommandBase.OnExecute(CommandLineApplication app, IConsole console) in /usr/oryx/src/BuildScriptGeneratorCli/Commands/CommandBase.cs:line 84
Command 'starter.sh oryx build /tmp ...' was aborted due to no output nor CPU activity for 60 seconds. You can increase the SCM_COMMAND_IDLE_TIMEOUT app setting (or WEBJOBS_IDLE_TIMEOUT if this is a WebJob) if needed.\nstarter.sh oryx build /tmp/zipdeploy/extracted -o /tmp/build/expressbuild --platform python --platform-version 3.10.4 -i /tmp/8db40c6ac818225 -p packagedir=.python_packages/lib/site-packages
One or more errors occurred. (Command 'starter.sh oryx build /tmp ...' was aborted due to no output nor CPU activity for 60 seconds. You can increase the SCM_COMMAND_IDLE_TIMEOUT app setting (or WEBJOBS_IDLE_TIMEOUT if this is a WebJob) if needed.\nstarter.sh 
oryx build /tmp/zipdeploy/extracted -o /tmp/build/expressbuild --platform python --platform-version 3.10.4 -i /tmp/8db40c6ac818225 -p packagedir=.python_packages/lib/site-packages)
Command 'starter.sh oryx build /tmp ...' was aborted due to no output nor CPU activity for 60 seconds. You can increase the SCM_COMMAND_IDLE_TIMEOUT app setting (or WEBJOBS_IDLE_TIMEOUT if this is a WebJob) if needed.\nstarter.sh oryx build /tmp/zipdeploy/extracted -o /tmp/build/expressbuild --platform python --platform-version 3.10.4 -i /tmp/8db40c6ac818225 -p packagedir=.python_packages/lib/site-packages
Generating summary of Oryx build
Deployment Log file does not exist in /tmp/oryx-build.log
The logfile at /tmp/oryx-build.log is empty. Unable to fetch the summary of build
Deployment Failed. deployer = Push-Deployer deploymentPath = Functions App ZipDeploy. Extract zip. Remote build.
Remote build failed!
```

Can you help us to understand how can we reach the "oryx-cdn.microsoft.io" via our own proxy server please while performing a remote build.

**Comment by harryli0108** [comment]
Hi @abhendu123 Thank you for filing this issue! From your description, it seems like the proxy server you're using is blocking the oryx-cdn traffic. I'm not sure if the environment you're using is based on app service environment or VNet. But, if possible, please check if
1. the webapp is allowing outbound traffic of oryx-cdn on port 443,
2. your proxy is also allowing the same traffic, and in my opinion, preferably on port 443 as well.

Please let me know if it helps! Feel free to let me know if there's any other issues I could help with.

**Comment by simonjj** [comment]
This issue seems resolved. Will be closing this issue. If this is still relevant and impacting you please open a new issue and link back to this issue for reference.

**Comment by MIBS-YN** [comment]
Hi, we are having the same exact issue and trying to find how to allow our App Service with VNet integration to access oryx-cdn.microsoft.io (and pypi.org and files.pythonhosted.org).

I finally found this thread, but this issue seems to be already closed without any solution described...

Could anyone who found solution please post how to solve this issue?
