### ISSUE TITLE
Flask-SocketIO: Current transport is: polling

### ISSUE THREAD

**Issue by huislaw** [microsoft/Oryx#2039]
I try to deploy this example to Azure Web App (Python: 3.10)
https://github.com/miguelgrinberg/Flask-SocketIO/tree/main/example

It can works after these steps:
1. Installed:
gevent
gevent-websocket

2. Added to requirements.txt:
gevent
gevent-websocket

3. Added .deployment
[config]
SCM_DO_BUILD_DURING_DEPLOYMENT=true

However, as screen cap below, 
it is showing **Current transport is: polling**
In my local machine it is **websocket**

How can I make it to be websocket on Azure Web App?

![image](https://github.com/microsoft/Oryx/assets/2201663/77e84435-0293-4657-8eae-d8e4ec85632d)

**Comment by huislaw** [comment]
I enabled the logging and get this error:

```
2023-07-11T02:52:34.713560621Z 169.254.129.1 - - [11/Jul/2023:02:52:34 +0000] "GET /socket.io/?EIO=4&transport=polling&t=Ob2tBkw&sid=KAO50umO--ZJ-IJ8AAAE HTTP/1.1" 200 306 "https://testhssocketio.azurewebsites.net/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/114.0"

2023-07-11T02:52:34.713520221Z [2023-07-11 02:52:34 +0000] [72] [ERROR] Socket error processing request.

2023-07-11T02:52:34.713585421Z Traceback (most recent call last):

2023-07-11T02:52:34.713589421Z   File "/opt/python/3.11.3/lib/python3.11/site-packages/gunicorn/workers/sync.py", line 136, in handle

2023-07-11T02:52:34.713593722Z     self.handle_request(listener, req, client, addr)

2023-07-11T02:52:34.713597422Z   File "/opt/python/3.11.3/lib/python3.11/site-packages/gunicorn/workers/sync.py", line 194, in handle_request

2023-07-11T02:52:34.713601522Z     util.reraise(*sys.exc_info())

2023-07-11T02:52:34.713605122Z   File "/opt/python/3.11.3/lib/python3.11/site-packages/gunicorn/util.py", line 626, in reraise

2023-07-11T02:52:34.713609222Z     raise value

2023-07-11T02:52:34.713614622Z   File "/opt/python/3.11.3/lib/python3.11/site-packages/gunicorn/workers/sync.py", line 186, in handle_request

2023-07-11T02:52:34.713620322Z     resp.close()

2023-07-11T02:52:34.713648422Z   File "/opt/python/3.11.3/lib/python3.11/site-packages/gunicorn/http/wsgi.py", line 393, in close

2023-07-11T02:52:34.713655722Z     util.write_chunk(self.sock, b"")

2023-07-11T02:52:34.713661522Z   File "/opt/python/3.11.3/lib/python3.11/site-packages/gunicorn/util.py", line 281, in write_chunk

2023-07-11T02:52:34.713667622Z     sock.sendall(chunk)

2023-07-11T02:52:34.713673323Z OSError: [Errno 9] Bad file descriptor

2023-07-11T02:52:36.332160363Z 169.254.129.1 - - [11/Jul/2023:02:52:36 +0000] "GET /socket.io/?EIO=4&transport=polling&t=Ob2tN7p HTTP/1.1" 200 97 "https://testhssocketio.azurewebsites.net/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/114.0"
```

Any idea how I can fix this ?
