### ISSUE TITLE
Getting error while using azure/webapps-deploy@v2

### ISSUE THREAD

**Issue by LajjaKhakhkhar** [microsoft/Oryx#2169]
Hi Everyone,

I am getting error while deploying python app, find below logs,

Error: Oops... An unexpected error has occurred.

Error: System.Xml.XmlException: Root element is missing.
 at System.Xml.XmlTextReaderImpl.Throw(Exception e)

 at System.Xml.XmlTextReaderImpl.ThrowWithoutLineInfo(String res)

at System.Xml.XmlTextReaderImpl.ParseDocumentContent()

at System.Xml.Linq.XDocument.Load(XmlReader reader, LoadOptions options)

at System.Xml.Linq.XDocument.Load(TextReader textReader, LoadOptions options)

 at Microsoft.Oryx.Detector.DotNetCore.ProjectFileHelpers.GetXmlDocument(ISourceRepo sourceRepo, String projectFile) in /usr/oryx/src/Detector/DotNetCore/ProjectFileProviders/ProjectFileHelpers.cs:line 82

  at Microsoft.Oryx.Detector.DotNetCore.ProjectFileHelpers.IsAzureBlazorWebAssemblyProject(ISourceRepo sourceRepo, String projectFile) in /usr/oryx/src/Detector/DotNetCore/ProjectFileProviders/ProjectFileHelpers.cs:line 32

   at Microsoft.Oryx.Detector.DotNetCore.ProbeAndFindProjectFileProvider.GetRelativePathToProjectFile(DetectorContext context) in /usr/oryx/src/Detector/DotNetCore/ProjectFileProviders/ProbeAndFindProjectFileProvider.cs:line 66

at Microsoft.Oryx.Detector.DotNetCore.DefaultProjectFileProvider.GetRelativePathToProjectFile(DetectorContext context) in /usr/oryx/src/Detector/DotNetCore/ProjectFileProviders/DefaultProjectFileProvider.cs:line 23
 at Microsoft.Oryx.Detector.DotNetCore.DotNetCoreDetector.Detect(DetectorContext context) in /usr/oryx/src/Detector/DotNetCore/DotnetCoreDetector.cs:line 37

 at Microsoft.Oryx.BuildScriptGenerator.DotNetCore.DotNetCorePlatform.Detect(RepositoryContext context) in /usr/oryx/src/BuildScriptGenerator/DotNetCore/DotnetCorePlatform.cs:line 89

  at Microsoft.Oryx.BuildScriptGenerator.DefaultPlatformsInformationProvider.GetPlatformsInfo(RepositoryContext context) in /usr/oryx/src/BuildScriptGenerator/DefaultPlatformsInformationProvider.cs:line 53

   at Microsoft.Oryx.BuildScriptGenerator.DefaultBuildScriptGenerator.GenerateBashScript(BuildScriptGeneratorContext context, String& script, List`1 checkerMessageSink) in /usr/oryx/src/BuildScriptGenerator/DefaultBuildScriptGenerator.cs:line 75

at Microsoft.Oryx.BuildScriptGeneratorCli.BuildScriptGenerator.TryGenerateScript(String& generatedScript, Exception& exception) in /usr/oryx/src/BuildScriptGeneratorCli/BuildScriptGenerator.cs:line 63
  at Microsoft.Oryx.BuildScriptGeneratorCli.BuildCommand.Execute(IServiceProvider serviceProvider, IConsole console) in /usr/oryx/src/BuildScriptGeneratorCli/Commands/BuildCommand.cs:line 278

  at Microsoft.Oryx.BuildScriptGeneratorCli.CommandBase.OnExecute(IConsole console) in /usr/oryx/src/BuildScriptGeneratorCli/Commands/CommandBase.cs:line 87

Error: Oops... An unexpected error has occurred.\nError: System.Xml.XmlException: Root element is missing.\n   at System.Xml.XmlTextReaderImpl.Throw(Exception e)\n   at System.Xml.XmlTextReaderImpl.ThrowWithoutLineInfo(String res)\n   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()\n   at System.Xml.Linq.XDocument.Load(XmlReader reader, LoadOptions options)\n   at System.Xml.Linq.XDocument.Load(TextReader textReader, LoadOptions options)\n   at Microsoft.Oryx.Detector.DotNetCore.ProjectFileHelpers.GetXmlDocument(ISourceRepo sourceRepo, String projectFile) in /usr/oryx/src/Detector/DotNetCore/ProjectFileProviders/ProjectFileHelpers.cs:line 82\n   at Microsoft.Oryx.Detector.DotNetCore.ProjectFileHelpers.IsAzureBlazorWebAssemblyProject(ISourceRepo sourceRepo, String projectFile) in /usr/oryx/src/Detector/DotNetCore/ProjectFileProviders/ProjectFileHelpers.cs:line 32\n   at Microsoft.Oryx.Detector.DotNetCore.ProbeAndFindProjectFileProvider.GetRelativePathToProjectFile(DetectorContext context) in /usr/oryx/src/Detector/DotNetCore/ProjectFileProviders/ProbeAndFindProjectFileProvider.cs:line 66\n   at Microsoft.Oryx.Detector.DotNetCore.DefaultProjectFileProvider.GetRelativePathToProjectFile(DetectorContext context) in /usr/oryx/src/Detector/DotNetCore/ProjectFileProviders/DefaultProjectFileProvider.cs:line 23\n   at Microsoft.Oryx.Detector.DotNetCore.DotNetCoreDetector.Detect(DetectorContext context) in /usr/oryx/src/Detector/DotNetCore/DotnetCoreDetector.cs:line 37\n   at Microsoft.Oryx.BuildScriptGenerator.DotNetCore.DotNetCorePlatform.Detect(RepositoryContext context) in /usr/oryx/src/BuildScriptGenerator/DotNetCore/DotnetCorePlatform.cs:line 89\n   at Microsoft.Oryx.BuildScriptGenerator.DefaultPlatformsInformationProvider.GetPlatformsInfo(RepositoryContext context) in /usr/oryx/src/BuildScriptGenerator/DefaultPlatformsInformationProvider.cs:line 53\n   at Microsoft.Oryx.BuildScriptGenerator.DefaultBuildScriptGenerator.GenerateBashScript(BuildScriptGeneratorContext context, String& script, List`1 checkerMessageSink) in /usr/oryx/src/BuildScriptGenerator/DefaultBuildScriptGenerator.cs:line 75\n   at Microsoft.Oryx.BuildScriptGeneratorCli.BuildScriptGenerator.TryGenerateScript(String& generatedScript, Exception& exception) in /usr/oryx/src/BuildScriptGeneratorCli/BuildScriptGenerator.cs:line 63\n   at Microsoft.Oryx.BuildScriptGeneratorCli.BuildCommand.Execute(IServiceProvider serviceProvider, IConsole console) in /usr/oryx/src/BuildScriptGeneratorCli/Commands/BuildCommand.cs:line 278\n   at Microsoft.Oryx.BuildScriptGeneratorCli.CommandBase.OnExecute(IConsole console) in /usr/oryx/src/BuildScriptGeneratorCli/Commands/CommandBase.cs:line 87\n/bin/bash -c "oryx build /tmp/zipdeploy/extracted -o /home/site/wwwroot --platform python --platform-version 3.10 -p virtualenv_name=antenv --log-file /tmp/build-debug.log  -i /tmp/8dbbff517c7d6bb --compress-destination-dir | tee /tmp/oryx-build.log ; exit $PIPESTATUS "

 
Generating summary of Oryx build
Parsing the build logs

Found 0 issue(s)
Build Summary :
===============

Errors (0)

Warnings (0)

Deployment Failed. deployer = GITHUB_ZIP_DEPLOY deploymentPath = ZipDeploy. Extract zip. Remote build.
Error: Failed to deploy web package to App Service.
Error: Deployment Failed, Package deployment using ZIP Deploy failed. Refer logs for more details.

Any help on this ?

**Comment by simonjj** [comment]
Thanks for raising this issue. This seems like a .NET app, would you be in a position to share the repo with us if it's still a relevant issue please.
