### ISSUE TITLE
Error building python azure-function

### ISSUE THREAD

**Issue by Krayushkin68** [microsoft/Oryx#2170]
### Bug Report

Hello, I am using python azure-function which uses two custom .whl packages. Until today everything was building and working fine. Today was another deployment with no dependencies changed, but this time a build error occurs. I've tried various ways to fix it (used all possible versions of the package that causes the error, all azure-function settings, rollbacks to old versions of my packages), but this deploy is not working. 
Building in the docker container mcr.microsoft.com/azure-functions/python:4-python3.9 works without problems.
Also tried to install packages from gitlab pypi registry, but this didn't help.
It works locally on a windows machine, and the deployment is done via vscode extension using zip deploy with remote build.
Thanks in advance.

Third party packages used in the custom packages:
pypdf~=3.9.1
pdfplumber~=0.10.2
camelot-py==0.11.0
python-dateutil~=2.8.2
pandas~=2.0.2
numpy~=1.24.3

local.settings.json
{
  "IsEncrypted": false,
  "Values": {
    "FUNCTIONS_WORKER_RUNTIME": "python",
    "AzureWebJobsStorage": "UseDevelopmentStorage=true",
    "AzureWebJobsFeatureFlags": "EnableWorkerIndexing"
  }
}

host.json
{
  "version": "2.0",
  "logging": {
    "applicationInsights": {
      "samplingSettings": {
        "isEnabled": true,
        "excludedTypes": "Request"
      }
    }
  },
  "extensionBundle": {
    "id": "Microsoft.Azure.Functions.ExtensionBundle",
    "version": "[4.*, 5.0.0)"
  }
}

Output log:

```
3:26:34 PM occ-test-fnc-parser: Starting deployment...
3:26:34 PM occ-test-fnc-parser: Creating zip package...
3:26:34 PM occ-test-fnc-parser: Zip package size: 167 kB
3:26:35 PM occ-test-fnc-parser: Fetching changes.
3:26:36 PM occ-test-fnc-parser: Cleaning up temp folders from previous zip deployments and extracting pushed zip file /tmp/zipdeploy/d0e1fd8a-036a-4d68-90a2-ababa2e74f36.zip (0.16 MB) to /tmp/zipdeploy/extracted
3:26:39 PM occ-test-fnc-parser: Updating submodules.
3:26:40 PM occ-test-fnc-parser: Preparing deployment for commit id '390252b9-8'.
3:26:40 PM occ-test-fnc-parser: PreDeployment: context.CleanOutputPath False
3:26:40 PM occ-test-fnc-parser: PreDeployment: context.OutputPath /home/site/wwwroot
3:26:40 PM occ-test-fnc-parser: Repository path is /tmp/zipdeploy/extracted
3:26:40 PM occ-test-fnc-parser: Running oryx build...
3:26:40 PM occ-test-fnc-parser: Command: oryx build /tmp/zipdeploy/extracted -o /home/site/wwwroot --platform python --platform-version 3.9.7 -p packagedir=.python_packages/lib/site-packages
3:26:42 PM occ-test-fnc-parser: Operation performed by Microsoft Oryx, https://github.com/Microsoft/Oryx
3:26:42 PM occ-test-fnc-parser: You can report issues at https://github.com/Microsoft/Oryx/issues
3:26:42 PM occ-test-fnc-parser: Oryx Version: 0.2.20210120.1, Commit: 66c7820d7df527aaffabd2563a49ad57930999c9, ReleaseTagName: 20210120.1
3:26:42 PM occ-test-fnc-parser: Build Operation ID: |ZA4FMuSICsE=.6e443ae6_
3:26:42 PM occ-test-fnc-parser: Repository Commit : 390252b9-8889-4961-b941-d614a3c44790
3:26:42 PM occ-test-fnc-parser: Detecting platforms...
3:27:13 PM occ-test-fnc-parser: Detected following platforms:
3:27:13 PM occ-test-fnc-parser:   python: 3.9.7
3:27:13 PM occ-test-fnc-parser: Version '3.9.7' of platform 'python' is not installed. Generating script to install it...
3:27:13 PM occ-test-fnc-parser: Source directory     : /tmp/zipdeploy/extracted
3:27:13 PM occ-test-fnc-parser: Destination directory: /home/site/wwwroot
3:27:13 PM occ-test-fnc-parser: Downloading and extracting 'python' version '3.9.7' to '/tmp/oryx/platforms/python/3.9.7'...
3:27:14 PM occ-test-fnc-parser: Downloaded in 1 sec(s).
3:27:14 PM occ-test-fnc-parser: Verifying checksum...
3:27:14 PM occ-test-fnc-parser: Extracting contents...
3:27:17 PM occ-test-fnc-parser: Done in 4 sec(s).
3:27:17 PM occ-test-fnc-parser: Python Version: /tmp/oryx/platforms/python/3.9.7/bin/python3.9
3:27:17 PM occ-test-fnc-parser: Running pip install...
3:27:18 PM occ-test-fnc-parser: [12:27:18+0000] Collecting azure-functions
3:27:18 PM occ-test-fnc-parser: [12:27:18+0000]   Downloading azure_functions-1.17.0-py3-none-any.whl (165 kB)
3:27:18 PM occ-test-fnc-parser: [12:27:18+0000] Processing ./packages/parser_pdf-0.1.6-py3-none-any.whl
3:27:18 PM occ-test-fnc-parser: [12:27:18+0000] Processing ./packages/parser_csv-0.1.0-py3-none-any.whl
3:27:18 PM occ-test-fnc-parser: [12:27:18+0000] Collecting camelot-py==0.11.0
3:27:19 PM occ-test-fnc-parser: [12:27:18+0000]   Downloading camelot_py-0.11.0-py3-none-any.whl (40 kB)
3:27:19 PM occ-test-fnc-parser: [12:27:19+0000] Collecting python-dateutil
3:27:19 PM occ-test-fnc-parser: [12:27:19+0000]   Downloading python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
3:27:19 PM occ-test-fnc-parser: [12:27:19+0000] Collecting pypdf~=3.9.1
3:27:19 PM occ-test-fnc-parser: [12:27:19+0000]   Downloading pypdf-3.9.1-py3-none-any.whl (249 kB)
3:27:19 PM occ-test-fnc-parser: [12:27:19+0000] Collecting pandas
3:27:20 PM occ-test-fnc-parser: [12:27:19+0000]   Downloading pandas-2.1.1-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (12.3 MB)
3:27:21 PM occ-test-fnc-parser: [12:27:21+0000] Collecting numpy
3:27:21 PM occ-test-fnc-parser: [12:27:21+0000]   Downloading numpy-1.26.0-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (18.2 MB)
3:27:22 PM occ-test-fnc-parser: [12:27:22+0000] Collecting pdfplumber==0.10.2
3:27:22 PM occ-test-fnc-parser: [12:27:22+0000]   Downloading pdfplumber-0.10.2-py3-none-any.whl (47 kB)
3:27:22 PM occ-test-fnc-parser: [12:27:22+0000] Collecting click>=6.7
3:27:22 PM occ-test-fnc-parser: [12:27:22+0000]   Downloading click-8.1.7-py3-none-any.whl (97 kB)
3:27:22 PM occ-test-fnc-parser: [12:27:22+0000] Collecting openpyxl>=2.5.8
3:27:22 PM occ-test-fnc-parser: [12:27:22+0000]   Downloading openpyxl-3.1.2-py2.py3-none-any.whl (249 kB)
3:27:22 PM occ-test-fnc-parser: [12:27:22+0000] Collecting chardet>=3.0.4
3:27:22 PM occ-test-fnc-parser: [12:27:22+0000]   Downloading chardet-5.2.0-py3-none-any.whl (199 kB)
3:27:22 PM occ-test-fnc-parser: [12:27:22+0000] Collecting tabulate>=0.8.9
3:27:22 PM occ-test-fnc-parser: [12:27:22+0000]   Downloading tabulate-0.9.0-py3-none-any.whl (35 kB)
3:27:22 PM occ-test-fnc-parser: [12:27:22+0000] Collecting pdfminer.six>=20200726
3:27:22 PM occ-test-fnc-parser: [12:27:22+0000]   Downloading pdfminer.six-20221105-py3-none-any.whl (5.6 MB)
3:27:23 PM occ-test-fnc-parser: [12:27:23+0000] Collecting six>=1.5
3:27:23 PM occ-test-fnc-parser: [12:27:23+0000]   Downloading six-1.16.0-py2.py3-none-any.whl (11 kB)
3:27:23 PM occ-test-fnc-parser: [12:27:23+0000] Collecting typing_extensions>=3.10.0.0; python_version < "3.10"
3:27:23 PM occ-test-fnc-parser: [12:27:23+0000]   Downloading typing_extensions-4.8.0-py3-none-any.whl (31 kB)
3:27:23 PM occ-test-fnc-parser: [12:27:23+0000] Collecting pytz>=2020.1
3:27:23 PM occ-test-fnc-parser: [12:27:23+0000]   Downloading pytz-2023.3.post1-py2.py3-none-any.whl (502 kB)
3:27:23 PM occ-test-fnc-parser: [12:27:23+0000] Collecting tzdata>=2022.1
3:27:23 PM occ-test-fnc-parser: [12:27:23+0000]   Downloading tzdata-2023.3-py2.py3-none-any.whl (341 kB)
3:27:24 PM occ-test-fnc-parser: [12:27:24+0000] Collecting pypdfium2>=4.18.0
3:27:24 PM occ-test-fnc-parser: [12:27:24+0000]   Downloading pypdfium2-4.20.0.tar.gz (145 kB)
3:27:24 PM occ-test-fnc-parser: [12:27:24+0000]   Installing build dependencies: started
3:27:36 PM occ-test-fnc-parser: [12:27:36+0000]   Installing build dependencies: finished with status 'done'
3:27:36 PM occ-test-fnc-parser: [12:27:36+0000]   Getting requirements to build wheel: started
3:27:37 PM occ-test-fnc-parser: [12:27:37+0000]   Getting requirements to build wheel: finished with status 'error'
3:27:37 PM occ-test-fnc-parser:   ERROR: Command errored out with exit status 1:
3:27:37 PM occ-test-fnc-parser:    command: /tmp/oryx/platforms/python/3.9.7/bin/python3.9 /tmp/oryx/platforms/python/3.9.7/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmpzpyqzoos
3:27:37 PM occ-test-fnc-parser:        cwd: /tmp/pip-install-deeabhxt/pypdfium2
3:27:37 PM occ-test-fnc-parser:   Complete output (49 lines):
3:27:37 PM occ-test-fnc-parser:   ['git', 'ls-remote', 'https://github.com/bblanchon/pdfium-binaries.git'] (cwd=None)
3:27:37 PM occ-test-fnc-parser:   Switching pdfium binary from None (v8 False) to 6029 (v8 False)
3:27:37 PM occ-test-fnc-parser:   ['ctypesgen', '--library', 'pdfium', '--runtime-libdir', '.', '--strip-build-path=/tmp/pip-install-deeabhxt/pypdfium2/data/linux_x64/build_tar/include', '--no-srcinfo', 'fpdf_annot.h', 'fpdf_attachment.h', 'fpdf_catalog.h', 'fpdf_dataavail.h', 'fpdf_doc.h', 'fpdf_edit.h', 'fpdf_ext.h', 'fpdf_flatten.h', 'fpdf_formfill.h', 'fpdf_fwlevent.h', 'fpdf_javascript.h', 'fpdf_ppo.h', 'fpdf_progressive.h', 'fpdf_save.h', 'fpdf_searchex.h', 'fpdf_signature.h', 'fpdf_structtree.h', 'fpdf_sysfontinfo.h', 'fpdf_text.h', 'fpdf_thumbnail.h', 'fpdf_transformpage.h', 'fpdfview.h', '-o', '/tmp/pip-install-deeabhxt/pypdfium2/data/linux_x64/raw.py'] (cwd=PosixPath('/tmp/pip-install-deeabhxt/pypdfium2/data/linux_x64/build_tar/include'))
3:27:37 PM occ-test-fnc-parser:   usage: ctypesgen [-h] [--version] -i HEADERS [HEADERS ...] -l LIBRARY
3:27:37 PM occ-test-fnc-parser:                    [-o FILE] [--other-headers HEADER [HEADER ...]]
3:27:37 PM occ-test-fnc-parser:                    [-m MODULE [MODULE ...]] [-I INCLUDEDIR [INCLUDEDIR ...]]
3:27:37 PM occ-test-fnc-parser:                    [-L LIBDIR [LIBDIR ...]]
3:27:37 PM occ-test-fnc-parser:                    [--compile-libdirs LIBDIR [LIBDIR ...]]
3:27:37 PM occ-test-fnc-parser:                    [--runtime-libdirs LIBDIR [LIBDIR ...]] [--no-embed-preamble]
3:27:37 PM occ-test-fnc-parser:                    [--cpp CPP] [--allow-gnu-c] [-D MACRO [MACRO ...]]
3:27:37 PM occ-test-fnc-parser:                    [-U NAME [NAME ...]] [--save-preprocessed-headers FILENAME]
3:27:37 PM occ-test-fnc-parser:                    [--optimize-lexer] [-a] [--builtin-symbols] [--no-macros]
3:27:37 PM occ-test-fnc-parser:                    [--no-undefs] [--include-symbols REGEXPR [REGEXPR ...]]
3:27:37 PM occ-test-fnc-parser:                    [--exclude-symbols REGEXPR [REGEXPR ...]] [--no-stddef-types]
3:27:37 PM occ-test-fnc-parser:                    [--no-gnu-types] [--no-python-types] [--no-load-library]
3:27:37 PM occ-test-fnc-parser:                    [--header-template TEMPLATE] [--strip-build-path BUILD_PATH]
3:27:37 PM occ-test-fnc-parser:                    [--insert-files FILENAME [FILENAME ...]]
3:27:37 PM occ-test-fnc-parser:                    [--output-language LANGUAGE] [--no-srcinfo]
3:27:37 PM occ-test-fnc-parser:                    [--no-symbol-guards] [--all-errors] [--show-long-errors]
3:27:37 PM occ-test-fnc-parser:                    [--no-macro-warnings] [--debug-level DEBUG_LEVEL]
3:27:37 PM occ-test-fnc-parser:   ctypesgen: error: the following arguments are required: -i/--include/--headers
3:27:37 PM occ-test-fnc-parser:   'https://github.com/bblanchon/pdfium-binaries/releases/download/chromium%2F6029/pdfium-linux-x64.tgz' -> '/tmp/pip-install-deeabhxt/pypdfium2/data/linux_x64/pdfium-linux-x64.tgz'
3:27:37 PM occ-test-fnc-parser:   Traceback (most recent call last):
3:27:37 PM occ-test-fnc-parser:     File "/tmp/oryx/platforms/python/3.9.7/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py", line 280, in <module>
3:27:37 PM occ-test-fnc-parser:       main()
3:27:37 PM occ-test-fnc-parser:     File "/tmp/oryx/platforms/python/3.9.7/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py", line 263, in main
3:27:37 PM occ-test-fnc-parser:       json_out['return_val'] = hook(**hook_input['kwargs'])
3:27:37 PM occ-test-fnc-parser:     File "/tmp/oryx/platforms/python/3.9.7/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py", line 114, in get_requires_for_build_wheel
3:27:37 PM occ-test-fnc-parser:       return hook(config_settings)
3:27:37 PM occ-test-fnc-parser:     File "/tmp/pip-build-env-9tdon_xy/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 355, in get_requires_for_build_wheel
3:27:37 PM occ-test-fnc-parser:       return self._get_build_requires(config_settings, requirements=['wheel'])
3:27:37 PM occ-test-fnc-parser:     File "/tmp/pip-build-env-9tdon_xy/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 325, in _get_build_requires
3:27:37 PM occ-test-fnc-parser:       self.run_setup()
3:27:37 PM occ-test-fnc-parser:     File "/tmp/pip-build-env-9tdon_xy/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 341, in run_setup
3:27:37 PM occ-test-fnc-parser:       exec(code, locals())
3:27:37 PM occ-test-fnc-parser:     File "<string>", line 87, in <module>
3:27:37 PM occ-test-fnc-parser:     File "<string>", line 81, in main
3:27:37 PM occ-test-fnc-parser:     File "<string>", line 61, in install_handler
3:27:37 PM occ-test-fnc-parser:     File "/tmp/pip-install-deeabhxt/pypdfium2/setupsrc/pypdfium2_setup/update_pdfium.py", line 154, in main
3:27:37 PM occ-test-fnc-parser:       generate_bindings(archives, version, use_v8)
3:27:37 PM occ-test-fnc-parser:     File "/tmp/pip-install-deeabhxt/pypdfium2/setupsrc/pypdfium2_setup/update_pdfium.py", line 131, in generate_bindings
3:27:37 PM occ-test-fnc-parser:       call_ctypesgen(pl_dir, build_dir/"include", use_v8)
3:27:37 PM occ-test-fnc-parser:     File "/tmp/pip-install-deeabhxt/pypdfium2/setupsrc/pypdfium2_setup/packaging_base.py", line 235, in call_ctypesgen
3:27:37 PM occ-test-fnc-parser:       run_cmd(args, cwd=include_dir)
3:27:37 PM occ-test-fnc-parser:     File "/tmp/pip-install-deeabhxt/pypdfium2/setupsrc/pypdfium2_setup/packaging_base.py", line 209, in run_cmd
3:27:37 PM occ-test-fnc-parser:       comp_process = subprocess.run(command, cwd=cwd, check=check, **kwargs)
3:27:37 PM occ-test-fnc-parser:     File "/tmp/oryx/platforms/python/3.9.7/lib/python3.9/subprocess.py", line 528, in run
3:27:37 PM occ-test-fnc-parser:       raise CalledProcessError(retcode, process.args,
3:27:37 PM occ-test-fnc-parser:   subprocess.CalledProcessError: Command '['ctypesgen', '--library', 'pdfium', '--runtime-libdir', '.', '--strip-build-path=/tmp/pip-install-deeabhxt/pypdfium2/data/linux_x64/build_tar/include', '--no-srcinfo', 'fpdf_annot.h', 'fpdf_attachment.h', 'fpdf_catalog.h', 'fpdf_dataavail.h', 'fpdf_doc.h', 'fpdf_edit.h', 'fpdf_ext.h', 'fpdf_flatten.h', 'fpdf_formfill.h', 'fpdf_fwlevent.h', 'fpdf_javascript.h', 'fpdf_ppo.h', 'fpdf_progressive.h', 'fpdf_save.h', 'fpdf_searchex.h', 'fpdf_signature.h', 'fpdf_structtree.h', 'fpdf_sysfontinfo.h', 'fpdf_text.h', 'fpdf_thumbnail.h', 'fpdf_transformpage.h', 'fpdfview.h', '-o', '/tmp/pip-install-deeabhxt/pypdfium2/data/linux_x64/raw.py']' returned non-zero exit status 2.
3:27:37 PM occ-test-fnc-parser:   ----------------------------------------
3:27:37 PM occ-test-fnc-parser: ERROR: Command errored out with exit status 1: /tmp/oryx/platforms/python/3.9.7/bin/python3.9 /tmp/oryx/platforms/python/3.9.7/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmpzpyqzoos Check the logs for full command output.
3:27:38 PM occ-test-fnc-parser: WARNING: You are using pip version 20.2.3; however, version 23.2.1 is available.
3:27:38 PM occ-test-fnc-parser: You should consider upgrading via the '/tmp/oryx/platforms/python/3.9.7/bin/python3.9 -m pip install --upgrade pip' command.
3:27:38 PM occ-test-fnc-parser: Done in 21 sec(s).
3:27:39 PM occ-test-fnc-parser: ERROR: Command errored out with exit status 1:
3:27:39 PM occ-test-fnc-parser: /opt/Kudu/Scripts/starter.sh oryx build /tmp/zipdeploy/extracted -o /home/site/wwwroot --platform python --platform-version 3.9.7 -p packagedir=.python_packages/lib/site-packages
3:27:39 PM occ-test-fnc-parser: Generating summary of Oryx build
3:27:39 PM occ-test-fnc-parser: Deployment Log file does not exist in /tmp/oryx-build.log
3:27:39 PM occ-test-fnc-parser: The logfile at /tmp/oryx-build.log is empty. Unable to fetch the summary of build
3:27:39 PM occ-test-fnc-parser: Deployment Failed. deployer = ms-azuretools-vscode deploymentPath = Functions App ZipDeploy. Extract zip. Remote build.
3:27:45 PM occ-test-fnc-parser: Deployment failed.
```

**Comment by chandru4ni** [comment]
I am facing the same issue with the same package. I removed the package pypdfium2 from requirements.txt but it is trying to use the cached copy and giving the same error. In local it works correctly and while deployment I am facing this issue.

**Comment by Krayushkin68** [comment]
I tried deploying the same version today and it worked.... 
I don't know what changed in Oryx or Azure during that time, but the problem is solved for me.

**Comment by Krayushkin68** [comment]
@guillaumedelande Sorry, as I said, I just waited for a while without touching the project. During that time I was using the docker-deployed version. And after that I just re-deployed the exact same version to the exact same azure function service.
The only thing that was changed is that I recreated venv and reinstalled the azure functions plugin in vscode, but I don't think that was the case.

**Comment by chandru4ni** [comment]
What I found is, there are list of packages that Azure considers as whitelisted packages, if the package installed does not belong to list of whitelisted packages we kind these kind of errors. I resolved it by replacing this package with an alternative package. The package pdfplumber caused this issue in my case.

**Comment by guillaumedelande** [comment]
Did you explicitly add pypdfium2 in the requirements.txt file? At first I didn't because I was using pdfplumber, which seemed to need that dependency. It seems to have solved the issue by adding pypdfium2 to the requirements.txt (not 100% sure because I also have issues with installing torch, hence unable to test the library). Then you might have to try a couple of different versions. In my case this version works (machine is Linux with python 3.9.7):
```
3:39:05 PM XXX: [14:39:05+0000] Collecting pypdfium2
3:39:05 PM XXX: [14:39:05+0000]   Downloading pypdfium2-3.21.1-py3-none-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.8 MB)
```

**Comment by chandru4ni** [comment]
You are right, python version played a role in this. Made the local python version and the one on Azure the same but still was able to solve using pdfplumber. But pypdfium2 helped and able to proceed. thanks.
