### ISSUE TITLE
Issue with nodejs deployment

### ISSUE THREAD

**Issue by hd-vt** [microsoft/Oryx#2398]
### Bug Report

- At what date and time did you most recently experience the problem?
27-Mar-2024, 20:23IST

- Where did you experience the problem? E.g. Azure Web Apps, Azure Functions, Azure Container Registry, or offline use.
Azure Web Apps

- If your repo is publicly available please share its URL:
not available

- What happened?
gives error: of some internal json library, 

- What did you expect or want to happen?
successfull build and deploy of node js project

- How can we reproduce it?
i can share you source code privately for debugging purpose.

- Do you have log output? Please include between the backticks:

```
Command: oryx build /tmp/zipdeploy/extracted -o /home/site/wwwroot --platform nodejs --platform-version 20 -p virtualenv_name= --log-file /tmp/build-debug.log  -i /tmp/8dc4e6d6f5de13d -p compress_node_modules=tar-gz | tee /tmp/oryx-build.log
Operation performed by Microsoft Oryx, https://github.com/Microsoft/Oryx
You can report issues at https://github.com/Microsoft/Oryx/issues

Oryx Version: 0.2.20230829.1, Commit: 5bd3088141516cdbd815d62ada052654e91f0429, ReleaseTagName: 20230829.1

Build Operation ID: 645007868151dcee
Repository Commit : c68bd677-b738-4643-8855-9fe3868f9fdd
OS Type           : bookworm
Image Type        : githubactions

Detecting platforms...
Error: Oops... An unexpected error has occurred.
Error: Newtonsoft.Json.JsonReaderException: Error reading JObject from JsonReader. Current JsonReader item is not an object: StartArray. Path '', line 1, position 1.
   at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JObject.Parse(String json, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JObject.Parse(String json)
   at Microsoft.Oryx.Detector.ParserHelper.ParseJsonFile(ISourceRepo sourceRepo, String filePath) in /usr/oryx/src/Detector/ParserHelper.cs:line 86
   at Microsoft.Oryx.Detector.Hugo.HugoDetector.IsHugoJsonFile(ISourceRepo sourceRepo, String[] subPaths) in /usr/oryx/src/Detector/Hugo/HugoDetector.cs:line 229
   at Microsoft.Oryx.Detector.Hugo.HugoDetector.IsHugoApp(ISourceRepo sourceRepo, String& appDirectory) in /usr/oryx/src/Detector/Hugo/HugoDetector.cs:line 157
   at Microsoft.Oryx.Detector.Hugo.HugoDetector.Detect(DetectorContext context) in /usr/oryx/src/Detector/Hugo/HugoDetector.cs:line 49
   at Microsoft.Oryx.BuildScriptGenerator.Hugo.HugoPlatform.Detect(RepositoryContext context) in /usr/oryx/src/BuildScriptGenerator/Hugo/HugoPlatform.cs:line 61
   at Microsoft.Oryx.BuildScriptGenerator.DefaultPlatformsInformationProvider.GetPlatformsInfo(RepositoryContext context) in /usr/oryx/src/BuildScriptGenerator/DefaultPlatformsInformationProvider.cs:line 53
   at Microsoft.Oryx.BuildScriptGenerator.DefaultBuildScriptGenerator.GenerateBashScript(BuildScriptGeneratorContext context, String& script, List`1 checkerMessageSink) in /usr/oryx/src/BuildScriptGenerator/DefaultBuildScriptGenerator.cs:line 75
   at Microsoft.Oryx.BuildScriptGeneratorCli.BuildScriptGenerator.TryGenerateScript(String& generatedScript, Exception& exception) in /usr/oryx/src/BuildScriptGeneratorCli/BuildScriptGenerator.cs:line 63
   at Microsoft.Oryx.BuildScriptGeneratorCli.BuildCommand.Execute(IServiceProvider serviceProvider, IConsole console) in /usr/oryx/src/BuildScriptGeneratorCli/Commands/BuildCommand.cs:line 278
   at Microsoft.Oryx.BuildScriptGeneratorCli.CommandBase.OnExecute(IConsole console) in /usr/oryx/src/BuildScriptGeneratorCli/Commands/CommandBase.cs:line 87
Error: Oops... An unexpected error has occurred.\nError: Newtonsoft.Json.JsonReaderException: Error reading JObject from JsonReader. Current JsonReader item is not an object: StartArray. Path '', line 1, position 1.\n   at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)\n   at Newtonsoft.Json.Linq.JObject.Parse(String json, JsonLoadSettings settings)\n   at Newtonsoft.Json.Linq.JObject.Parse(String json)\n   at Microsoft.Oryx.Detector.ParserHelper.ParseJsonFile(ISourceRepo sourceRepo, String filePath) in /usr/oryx/src/Detector/ParserHelper.cs:line 86\n   at Microsoft.Oryx.Detector.Hugo.HugoDetector.IsHugoJsonFile(ISourceRepo sourceRepo, String[] subPaths) in /usr/oryx/src/Detector/Hugo/HugoDetector.cs:line 229\n   at Microsoft.Oryx.Detector.Hugo.HugoDetector.IsHugoApp(ISourceRepo sourceRepo, String& appDirectory) in /usr/oryx/src/Detector/Hugo/HugoDetector.cs:line 157\n   at Microsoft.Oryx.Detector.Hugo.HugoDetector.Detect(DetectorContext context) in /usr/oryx/src/Detector/Hugo/HugoDetector.cs:line 49\n   at Microsoft.Oryx.BuildScriptGenerator.Hugo.HugoPlatform.Detect(RepositoryContext context) in /usr/oryx/src/BuildScriptGenerator/Hugo/HugoPlatform.cs:line 61\n   at Microsoft.Oryx.BuildScriptGenerator.DefaultPlatformsInformationProvider.GetPlatformsInfo(RepositoryContext context) in /usr/oryx/src/BuildScriptGenerator/DefaultPlatformsInformationProvider.cs:line 53\n   at Microsoft.Oryx.BuildScriptGenerator.DefaultBuildScriptGenerator.GenerateBashScript(BuildScriptGeneratorContext context, String& script, List`1 checkerMessageSink) in /usr/oryx/src/BuildScriptGenerator/DefaultBuildScriptGenerator.cs:line 75\n   at Microsoft.Oryx.BuildScriptGeneratorCli.BuildScriptGenerator.TryGenerateScript(String& generatedScript, Exception& exception) in /usr/oryx/src/BuildScriptGeneratorCli/BuildScriptGenerator.cs:line 63\n   at Microsoft.Oryx.BuildScriptGeneratorCli.BuildCommand.Execute(IServiceProvider serviceProvider, IConsole console) in /usr/oryx/src/BuildScriptGeneratorCli/Commands/BuildCommand.cs:line 278\n   at Microsoft.Oryx.BuildScriptGeneratorCli.CommandBase.OnExecute(IConsole console) in /usr/oryx/src/BuildScriptGeneratorCli/Commands/CommandBase.cs:line 87\n/bin/bash -c "oryx build /tmp/zipdeploy/extracted -o /home/site/wwwroot --platform nodejs --platform-version 20 -p virtualenv_name= --log-file /tmp/build-debug.log  -i /tmp/8dc4e6d6f5de13d -p compress_node_modules=tar-gz | tee /tmp/oryx-build.log ; exit $PIPESTATUS "
```

**Comment by hd-vt** [comment]
Full Log

`8:30:31 PM: Starting "vtims"...
8:30:33 PM: "vtims" has been started.
8:30:36 PM: Checking app settings...
8:30:38 PM: Initializing SSH...
8:30:38 PM: [Tunnel] Pinging app default url...
8:31:48 PM vtims: Starting deployment...
8:31:49 PM vtims: Creating zip package...
8:31:50 PM vtims: Ignoring files from "appService.zipIgnorePattern"
"node_modules{,/**}"
".vscode{,/**}"
8:31:52 PM vtims: Adding 121 files to zip package...
8:31:52 PM vtims: c:\Users\hd\Downloads\ims\api\services\stock.service.js
8:31:52 PM vtims: c:\Users\hd\Downloads\ims\api\services\serve-static.service.js
8:31:52 PM vtims: c:\Users\hd\Downloads\ims\api\services\project.service.js
8:31:52 PM vtims: c:\Users\hd\Downloads\ims\api\services\location.service.js
8:31:52 PM vtims: c:\Users\hd\Downloads\ims\api\services\licence\licence.service.js
8:31:52 PM vtims: c:\Users\hd\Downloads\ims\api\services\licence\licence.interface.js
8:31:52 PM vtims: c:\Users\hd\Downloads\ims\api\services\licence\licence.helper.js
8:31:52 PM vtims: c:\Users\hd\Downloads\ims\api\services\licence\licence.env.js
8:31:52 PM vtims: c:\Users\hd\Downloads\ims\api\services\licence\licence.consts.js
8:31:52 PM vtims: c:\Users\hd\Downloads\ims\api\services\licence\licence.config.js
8:31:52 PM vtims: c:\Users\hd\Downloads\ims\api\services\cronjob.service.js
8:31:52 PM vtims: c:\Users\hd\Downloads\ims\api\services\chemical-usage.service.js
8:31:52 PM vtims: c:\Users\hd\Downloads\ims\api\services\axios.service.js
8:31:52 PM vtims: c:\Users\hd\Downloads\ims\api\services\auditlog.service.js
8:31:52 PM vtims: c:\Users\hd\Downloads\ims\api\server.js
8:31:52 PM vtims: c:\Users\hd\Downloads\ims\api\routes.js
8:31:52 PM vtims: c:\Users\hd\Downloads\ims\api\public\ril-ims\chemical\water_1710244779613.jpg
8:31:52 PM vtims: c:\Users\hd\Downloads\ims\api\public\ril-ims\chemical\toluene_1711018551103.jpg
8:31:52 PM vtims: c:\Users\hd\Downloads\ims\api\public\ril-ims\chemical\sulphuric-acid_1710245171963.jpg
8:31:52 PM vtims: c:\Users\hd\Downloads\ims\api\public\ril-ims\chemical\Sodium-hydroxide_1710246448598.jpg
8:31:52 PM vtims: c:\Users\hd\Downloads\ims\api\public\ril-ims\chemical\salt_1709877105687.jpg
8:31:52 PM vtims: c:\Users\hd\Downloads\ims\api\public\ril-ims\chemical\Potassium_hydroxide_1710257383779.webp
8:31:52 PM vtims: c:\Users\hd\Downloads\ims\api\public\ril-ims\chemical\phosphoric-acid_1711018632524.jpg
8:31:52 PM vtims: c:\Users\hd\Downloads\ims\api\public\ril-ims\chemical\nitric-acid_1710245967929.jpg
8:31:52 PM vtims: c:\Users\hd\Downloads\ims\api\public\ril-ims\chemical\methanol_1710257575079.jpg
8:31:52 PM vtims: c:\Users\hd\Downloads\ims\api\public\ril-ims\chemical\hydrogen-peroxide_1711018405354.jpg
8:31:52 PM vtims: c:\Users\hd\Downloads\ims\api\public\ril-ims\chemical\hydrochloric-acid-bottle-RNEJBD_1710245062429.jpg
8:31:52 PM vtims: c:\Users\hd\Downloads\ims\api\public\ril-ims\chemical\h2o_1710476833892.jpg
8:31:52 PM vtims: c:\Users\hd\Downloads\ims\api\public\ril-ims\chemical\Formaldehyde_1711018593059.jpg
8:31:52 PM vtims: c:\Users\hd\Downloads\ims\api\public\ril-ims\chemical\ethanol_1710245290304.webp
8:31:52 PM vtims: c:\Users\hd\Downloads\ims\api\public\ril-ims\chemical\benzene_1711018508678.jpeg
8:31:52 PM vtims: c:\Users\hd\Downloads\ims\api\public\ril-ims\chemical\Asetic-acid_1710245787877.webp
8:31:52 PM vtims: c:\Users\hd\Downloads\ims\api\public\ril-ims\chemical\Ammonium-hydroxide_1710246228234.webp
8:31:52 PM vtims: c:\Users\hd\Downloads\ims\api\public\ril-ims\chemical\Acetone_1710257743661.jpeg
8:31:52 PM vtims: c:\Users\hd\Downloads\ims\api\package.json
8:31:52 PM vtims: c:\Users\hd\Downloads\ims\api\package-lock.json
8:31:52 PM vtims: c:\Users\hd\Downloads\ims\api\modules\v1\chemical-usage\chemical-usage.schema.js
8:31:52 PM vtims: c:\Users\hd\Downloads\ims\api\modules\v1\chemical-usage\chemical-usage.routes.js
8:31:52 PM vtims: c:\Users\hd\Downloads\ims\api\modules\v1\chemical-usage\chemical-usage.controller.js
8:31:52 PM vtims: c:\Users\hd\Downloads\ims\api\modules\v1\user\user.routes.js
8:31:52 PM vtims: c:\Users\hd\Downloads\ims\api\modules\v1\user\user.controller.js
8:31:52 PM vtims: c:\Users\hd\Downloads\ims\api\modules\v1\user\user.schema.js
8:31:52 PM vtims: c:\Users\hd\Downloads\ims\api\modules\v1\role\role.schema.js
8:31:52 PM vtims: c:\Users\hd\Downloads\ims\api\modules\v1\role\role.routes.js
8:31:52 PM vtims: c:\Users\hd\Downloads\ims\api\modules\v1\role\role.controller.js
8:31:52 PM vtims: c:\Users\hd\Downloads\ims\api\modules\v1\stock\stock.schema.js
8:31:52 PM vtims: c:\Users\hd\Downloads\ims\api\modules\v1\stock\stock.routes.js
8:31:52 PM vtims: c:\Users\hd\Downloads\ims\api\modules\v1\stock\stock.controller.js
8:31:52 PM vtims: c:\Users\hd\Downloads\ims\api\models\tbl_user.model.js
8:31:52 PM vtims: c:\Users\hd\Downloads\ims\api\modules\v1\rack\rack.schema.js
8:31:52 PM vtims: c:\Users\hd\Downloads\ims\api\modules\v1\rack\rack.routes.js
8:31:52 PM vtims: c:\Users\hd\Downloads\ims\api\modules\v1\rack\rack.controller.js
8:31:52 PM vtims: c:\Users\hd\Downloads\ims\api\modules\v1\report\report.schema.js
8:31:52 PM vtims: c:\Users\hd\Downloads\ims\api\modules\v1\report\report.routes.js
8:31:52 PM vtims: c:\Users\hd\Downloads\ims\api\modules\v1\report\report.controller.js
8:31:52 PM vtims: c:\Users\hd\Downloads\ims\api\modules\v1\module\module.controller.js
8:31:52 PM vtims: c:\Users\hd\Downloads\ims\api\models\tbl_stock.model.js
8:31:52 PM vtims: c:\Users\hd\Downloads\ims\api\modules\v1\permission\permission.schema.js
8:31:52 PM vtims: c:\Users\hd\Downloads\ims\api\modules\v1\module\module.schema.js
8:31:52 PM vtims: c:\Users\hd\Downloads\ims\api\modules\v1\permission\permission.routes.js
8:31:52 PM vtims: c:\Users\hd\Downloads\ims\api\modules\v1\module\module.routes.js
8:31:52 PM vtims: c:\Users\hd\Downloads\ims\api\modules\v1\permission\permission.controller.js
8:31:52 PM vtims: c:\Users\hd\Downloads\ims\api\models\tbl_role.model.js
8:31:52 PM vtims: c:\Users\hd\Downloads\ims\api\models\tbl_permission.model.js
8:31:52 PM vtims: c:\Users\hd\Downloads\ims\api\modules\v1\drawer\drawer.routes.js
8:31:52 PM vtims: c:\Users\hd\Downloads\ims\api\modules\v1\drawer\drawer.controller.js
8:31:52 PM vtims: c:\Users\hd\Downloads\ims\api\modules\v1\lab\lab.schema.js
8:31:52 PM vtims: c:\Users\hd\Downloads\ims\api\modules\v1\lab\lab.routes.js
8:31:52 PM vtims: c:\Users\hd\Downloads\ims\api\modules\v1\location\location.schema.js
8:31:52 PM vtims: c:\Users\hd\Downloads\ims\api\modules\v1\lab\lab.controller.js
8:31:52 PM vtims: c:\Users\hd\Downloads\ims\api\modules\v1\location\location.routes.js
8:31:52 PM vtims: c:\Users\hd\Downloads\ims\api\modules\v1\location\location.controller.js
8:31:52 PM vtims: c:\Users\hd\Downloads\ims\api\modules\v1\manufacturer\manufacturer.schema.js
8:31:52 PM vtims: c:\Users\hd\Downloads\ims\api\modules\v1\drawer\drawer.schema.js
8:31:52 PM vtims: c:\Users\hd\Downloads\ims\api\modules\v1\manufacturer\manufacturer.routes.js
8:31:52 PM vtims: c:\Users\hd\Downloads\ims\api\modules\v1\manufacturer\manufacturer.controller.js
8:31:52 PM vtims: c:\Users\hd\Downloads\ims\api\models\tbl_module.model.js
8:31:52 PM vtims: c:\Users\hd\Downloads\ims\api\models\tbl_chemical_usage_history.model.js
8:31:52 PM vtims: c:\Users\hd\Downloads\ims\api\models\tbl_auditlog.model.js
8:31:52 PM vtims: c:\Users\hd\Downloads\ims\api\models\master_tbl.model.js
8:31:52 PM vtims: c:\Users\hd\Downloads\ims\api\models\master_rack.model.js
8:31:52 PM vtims: c:\Users\hd\Downloads\ims\api\models\master_manufacturer.model.js
8:31:52 PM vtims: c:\Users\hd\Downloads\ims\api\models\master_location.model.js
8:31:52 PM vtims: c:\Users\hd\Downloads\ims\api\models\master_drawer.js
8:31:52 PM vtims: c:\Users\hd\Downloads\ims\api\models\master_chemical.model.js
8:31:52 PM vtims: c:\Users\hd\Downloads\ims\api\models\index.js
8:31:52 PM vtims: c:\Users\hd\Downloads\ims\api\modules\v1\chemical\chemical.schema.js
8:31:52 PM vtims: c:\Users\hd\Downloads\ims\api\modules\v1\chemical\chemical.routes.js
8:31:52 PM vtims: c:\Users\hd\Downloads\ims\api\modules\v1\auth\auth.schema.js
8:31:52 PM vtims: c:\Users\hd\Downloads\ims\api\modules\v1\chemical\chemical.controller.js
8:31:52 PM vtims: c:\Users\hd\Downloads\ims\api\modules\v1\auth\auth.routes.js
8:31:52 PM vtims: c:\Users\hd\Downloads\ims\api\modules\v1\auth\auth.controller.js
8:31:52 PM vtims: c:\Users\hd\Downloads\ims\api\modules\v1\dashboard\dashbord.routes.js
8:31:52 PM vtims: c:\Users\hd\Downloads\ims\api\modules\v1\dashboard\dashboard.controller.js
8:31:52 PM vtims: c:\Users\hd\Downloads\ims\api\middleware\error.middleware.js
8:31:52 PM vtims: c:\Users\hd\Downloads\ims\api\middleware\licence.middleware.js
8:31:52 PM vtims: c:\Users\hd\Downloads\ims\api\middleware\logger.middleware.js
8:31:52 PM vtims: c:\Users\hd\Downloads\ims\api\middleware\auth.middleware.js
8:31:52 PM vtims: c:\Users\hd\Downloads\ims\api\logs\error.log
8:31:52 PM vtims: c:\Users\hd\Downloads\ims\api\middleware\validate.middleware.js
8:31:52 PM vtims: c:\Users\hd\Downloads\ims\api\middleware\project.middleware.js
8:31:52 PM vtims: c:\Users\hd\Downloads\ims\api\middleware\permission.middleware.js
8:31:52 PM vtims: c:\Users\hd\Downloads\ims\api\logs\http.log
8:31:52 PM vtims: c:\Users\hd\Downloads\ims\api\index.js
8:31:52 PM vtims: c:\Users\hd\Downloads\ims\api\interface\location.interface.js
8:31:52 PM vtims: c:\Users\hd\Downloads\ims\api\interface\auth.interface.js
8:31:52 PM vtims: c:\Users\hd\Downloads\ims\api\interface\project.interface.js
8:31:52 PM vtims: c:\Users\hd\Downloads\ims\api\locales\en\translation.json
8:31:52 PM vtims: c:\Users\hd\Downloads\ims\api\config\constant.config.js
8:31:52 PM vtims: c:\Users\hd\Downloads\ims\api\config\company.json
8:31:52 PM vtims: c:\Users\hd\Downloads\ims\api\helpers\util.js
8:31:52 PM vtims: c:\Users\hd\Downloads\ims\api\helpers\multer.js
8:31:52 PM vtims: c:\Users\hd\Downloads\ims\api\helpers\module.js
8:31:52 PM vtims: c:\Users\hd\Downloads\ims\api\helpers\logger.js
8:31:52 PM vtims: c:\Users\hd\Downloads\ims\api\helpers\jwt.js
8:31:52 PM vtims: c:\Users\hd\Downloads\ims\api\helpers\http.js
8:31:52 PM vtims: c:\Users\hd\Downloads\ims\api\helpers\constant.js
8:31:52 PM vtims: c:\Users\hd\Downloads\ims\api\helpers\config.js
8:31:52 PM vtims: c:\Users\hd\Downloads\ims\api\helpers\bcrypt.js
8:31:52 PM vtims: c:\Users\hd\Downloads\ims\api\.env
8:31:52 PM vtims: c:\Users\hd\Downloads\ims\api\.deployment
8:31:54 PM vtims: Zip package size: 1.15 MB
8:32:01 PM vtims: Updating submodules.
8:32:02 PM vtims: Preparing deployment for commit id 'e11aa7b3-b'.
8:32:02 PM vtims: PreDeployment: context.CleanOutputPath False
8:32:03 PM vtims: PreDeployment: context.OutputPath /home/site/wwwroot
8:32:03 PM vtims: Repository path is /tmp/zipdeploy/extracted
8:32:03 PM vtims: Running oryx build...
8:32:03 PM vtims: Command: oryx build /tmp/zipdeploy/extracted -o /home/site/wwwroot --platform nodejs --platform-version 20 -p virtualenv_name= --log-file /tmp/build-debug.log  -i /tmp/8dc4e6edc4157f4 -p compress_node_modules=tar-gz | tee /tmp/oryx-build.log
8:32:08 PM vtims: Operation performed by Microsoft Oryx, https://github.com/Microsoft/Oryx
8:32:08 PM vtims: You can report issues at https://github.com/Microsoft/Oryx/issues
8:32:09 PM vtims: Oryx Version: 0.2.20230829.1, Commit: 5bd3088141516cdbd815d62ada052654e91f0429, ReleaseTagName: 20230829.1
8:32:09 PM vtims: Build Operation ID: 63a4d22471345839
8:32:09 PM vtims: Repository Commit : e11aa7b3-bb61-468a-bf2f-4784606e62de
8:32:09 PM vtims: OS Type           : bookworm
8:32:09 PM vtims: Image Type        : githubactions
8:32:09 PM vtims: Detecting platforms...
8:32:36 PM vtims: Error: Oops... An unexpected error has occurred.
8:32:36 PM vtims: Error: Newtonsoft.Json.JsonReaderException: Error reading JObject from JsonReader. Current JsonReader item is not an object: StartArray. Path '', line 1, position 1.
8:32:36 PM vtims:    at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
8:32:37 PM vtims:    at Newtonsoft.Json.Linq.JObject.Parse(String json, JsonLoadSettings settings)
8:32:37 PM vtims:    at Newtonsoft.Json.Linq.JObject.Parse(String json)
8:32:37 PM vtims:    at Microsoft.Oryx.Detector.ParserHelper.ParseJsonFile(ISourceRepo sourceRepo, String filePath) in /usr/oryx/src/Detector/ParserHelper.cs:line 86
8:32:37 PM vtims:    at Microsoft.Oryx.Detector.Hugo.HugoDetector.IsHugoJsonFile(ISourceRepo sourceRepo, String[] subPaths) in /usr/oryx/src/Detector/Hugo/HugoDetector.cs:line 229
8:32:37 PM vtims:    at Microsoft.Oryx.Detector.Hugo.HugoDetector.IsHugoApp(ISourceRepo sourceRepo, String& appDirectory) in /usr/oryx/src/Detector/Hugo/HugoDetector.cs:line 157
8:32:37 PM vtims:    at Microsoft.Oryx.Detector.Hugo.HugoDetector.Detect(DetectorContext context) in /usr/oryx/src/Detector/Hugo/HugoDetector.cs:line 49
8:32:37 PM vtims:    at Microsoft.Oryx.BuildScriptGenerator.Hugo.HugoPlatform.Detect(RepositoryContext context) in /usr/oryx/src/BuildScriptGenerator/Hugo/HugoPlatform.cs:line 61
8:32:37 PM vtims:    at Microsoft.Oryx.BuildScriptGenerator.DefaultPlatformsInformationProvider.GetPlatformsInfo(RepositoryContext context) in /usr/oryx/src/BuildScriptGenerator/DefaultPlatformsInformationProvider.cs:line 53
8:32:37 PM vtims:    at Microsoft.Oryx.BuildScriptGenerator.DefaultBuildScriptGenerator.GenerateBashScript(BuildScriptGeneratorContext context, String& script, List`1 checkerMessageSink) in /usr/oryx/src/BuildScriptGenerator/DefaultBuildScriptGenerator.cs:line 75
8:32:37 PM vtims:    at Microsoft.Oryx.BuildScriptGeneratorCli.BuildScriptGenerator.TryGenerateScript(String& generatedScript, Exception& exception) in /usr/oryx/src/BuildScriptGeneratorCli/BuildScriptGenerator.cs:line 63
8:32:37 PM vtims:    at Microsoft.Oryx.BuildScriptGeneratorCli.BuildCommand.Execute(IServiceProvider serviceProvider, IConsole console) in /usr/oryx/src/BuildScriptGeneratorCli/Commands/BuildCommand.cs:line 278
8:32:37 PM vtims:    at Microsoft.Oryx.BuildScriptGeneratorCli.CommandBase.OnExecute(IConsole console) in /usr/oryx/src/BuildScriptGeneratorCli/Commands/CommandBase.cs:line 87
8:32:37 PM vtims: /bin/bash -c "oryx build /tmp/zipdeploy/extracted -o /home/site/wwwroot --platform nodejs --platform-version 20 -p virtualenv_name= --log-file /tmp/build-debug.log  -i /tmp/8dc4e6edc4157f4 -p compress_node_modules=tar-gz | tee /tmp/oryx-build.log ; exit $PIPESTATUS "
8:32:37 PM vtims: Generating summary of Oryx build
8:32:37 PM vtims: Parsing the build logs
8:32:37 PM vtims: Found 0 issue(s)
8:32:38 PM vtims: Build Summary :
8:32:38 PM vtims: ===============
8:32:38 PM vtims: Errors (0)
8:32:38 PM vtims: Warnings (0)
8:32:39 PM vtims: Deployment Failed. deployer = ms-azuretools-vscode deploymentPath = ZipDeploy. Extract zip.
8:33:01 PM vtims: Deployment failed.
`

**Comment by uddstrom** [comment]
Had the same issue. Appears to be caused by having a json file with an array in the project. 

This works:
{ "cars": ["Ford", "BMW", "Fiat"] }

But this breaks the build:
["Ford", "BMW", "Fiat"]
