### ISSUE TITLE
Django app fails during deployment on Azure after collectstatic after 40 minutes

### ISSUE THREAD

**Issue by ravi303** [microsoft/Oryx#2413]
### Bug Report

- At what date and time did you most recently experience the problem?
I have experienced this issues from 04/26/2024

- Where did you experience the problem? E.g. Azure Web Apps, Azure Functions, Azure Container Registry, or offline use.
Azure Web Apps.

- If your repo is publicly available please share its URL:
Code is not publicly available but it is a very simple newly created django app with just one view for the root url which says "hello word" and one python file (message_listener.py) which listens on a queue for messages using servicebus. Locally the code is working fine.

- What happened?
Sample Django app deployment was initially working fine and the default view upon navigating to the web app correctly displayed "hello world". After adding a message listener listening to a queue configured on servicebus and testing locally and validating that it is working fine. Regenerated the requirements.txt file as below,

asgiref==3.8.1
azure-core==1.30.1
azure-servicebus==7.12.1
certifi==2024.2.2
charset-normalizer==3.3.2
Django==5.0.4
idna==3.7
isodate==0.6.1
python-dotenv==1.0.1
requests==2.31.0
six==1.16.0
sqlparse==0.5.0
typing_extensions==4.11.0
tzdata==2024.1
urllib3==2.2.1
whitenoise==6.6.0

After re-zipping the project the deployment starts to hang for about 40 minutes on the collect static step,
2024-04-28T17:30:16.5370248Z Content in source directory is a Django app
2024-04-28T17:30:16.5961724Z Running collectstatic...
.
.
2024-04-28T18:09:13.4648221Z Exception Message : Deployment failed
2024-04-28T18:09:13.4877435Z Exception StackTrace :    at Kudu.Core.Deployment.DeploymentManager.DeployAsync(IRepository repository, ChangeSet changeSet, String deployer, Boolean clean, DeploymentInfoBase deploymentInfo, Boolean needFileUpdate, Boolean fullBuildByDefault) in /tmp/KuduLite/Kudu.Core/Deployment/DeploymentManager.cs:line 307
2024-04-28T18:09:13.4889736Z    at Kudu.Core.Deployment.FetchDeploymentManager.PerformDeployment(DeploymentInfoBase deploymentInfo, IDisposable tempDeployment, ChangeSet tempChangeSet, DeployStatusApiResult updateStatusObj) in /tmp/KuduLite/Kudu.Core/Deployment/FetchDeploymentManager.cs:line 258
2024-04-28T18:09:13.4931808Z    at Kudu.Core.Deployment.FetchDeploymentManager.PerformDeployment(DeploymentInfoBase deploymentInfo, IDisposable tempDeployment, ChangeSet tempChangeSet, DeployStatusApiResult updateStatusObj) in /tmp/KuduLite/Kudu.Core/Deployment/FetchDeploymentManager.cs:line 304
2024-04-28T18:09:13.5012115Z    at Kudu.Core.Deployment.FetchDeploymentManager.<>c__DisplayClass10_0.<<FetchDeploy>b__0>d.MoveNext() in /tmp/KuduLite/Kudu.Core/Deployment/FetchDeploymentManager.cs:line 148
2024-04-28T18:09:13.5030826Z --- End of stack trace from previous location ---
2024-04-28T18:09:13.5115844Z    at Kudu.Core.Deployment.FetchDeploymentManager.FetchDeploy(DeploymentInfoBase deployInfo, Boolean asyncRequested, Uri requestUri, String targetBranch) in /tmp/KuduLite/Kudu.Core/Deployment/FetchDeploymentManager.cs:line 141
2024-04-28T18:09:13.5128825Z    at Kudu.Services.Deployment.PushDeploymentController.PushDeployAsync(ArtifactDeploymentInfo deploymentInfo, Boolean isAsync, HttpContext context, JObject requestJson) in /tmp/KuduLite/Kudu.Services/Deployment/PushDeploymentController.cs:line 788
2024-04-28T18:09:13.5203420Z    at Kudu.Services.Deployment.PushDeploymentController.OneDeploy(String type, Boolean async, String path, Nullable`1 restart, Nullable`1 clean, Boolean ignoreStack, Boolean trackDeploymentProgress, Boolean trackStatus, Boolean reset) in /tmp/KuduLite/Kudu.Services/Deployment/PushDeploymentController.cs:line 614
2024-04-28T18:09:13.5212018Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
2024-04-28T18:09:13.5218292Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
2024-04-28T18:09:13.5223634Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
2024-04-28T18:09:13.5508959Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
2024-04-28T18:09:13.5520607Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
2024-04-28T18:09:13.5537851Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
2024-04-28T18:09:13.5621747Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
2024-04-28T18:09:13.5812886Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
2024-04-28T18:09:13.5822430Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
2024-04-28T18:09:13.5830562Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
2024-04-28T18:09:13.5836860Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
2024-04-28T18:09:13.5844025Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
2024-04-28T18:09:13.5939699Z    at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
2024-04-28T18:09:13.6047504Z    at Kudu.Services.Web.Tracing.TraceMiddleware.Invoke(HttpContext context) in /tmp/KuduLite/Kudu.Services.Web/Tracing/TraceMiddleware.cs:line 107
2024-04-28T18:09:13.6486006Z [41m[30mfail[39m[22m[49m: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[1]
2024-04-28T18:09:13.6523895Z       An unhandled exception has occurred while executing the request.
2024-04-28T18:09:13.6532435Z       ExitCode: 137, Output: Operation performed by Microsoft Oryx, https://github.com/Microsoft/Oryx
2024-04-28T18:09:13.6632970Z       You can report issues at https://github.com/Microsoft/Oryx/issues

- What did you expect or want to happen?
Deployment to complete successfully and application to work normally and listen to messages.

- How can we reproduce it?
Just a create a new sample Django app and write a message listener to listen to messages from a queue which is configured on service bus.
Deploy to Azure and watch the logs.

- Do you have log output? Please include between the backticks:

```
2024-04-28T17:30:16.2159307Z [17:29:58+0000]    â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â” 44.0/44.0 kB 1.1 MB/s eta 0:00:00
2024-04-28T17:30:16.2558680Z [17:29:58+0000] Downloading typing_extensions-4.11.0-py3-none-any.whl (34 kB)
2024-04-28T17:30:16.2732538Z [17:29:58+0000] Downloading tzdata-2024.1-py2.py3-none-any.whl (345 kB)
2024-04-28T17:30:16.2939971Z [17:29:58+0000]    â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â” 345.4/345.4 kB 10.6 MB/s eta 0:00:00
2024-04-28T17:30:16.3355582Z [17:29:58+0000] Downloading urllib3-2.2.1-py3-none-any.whl (121 kB)
2024-04-28T17:30:16.3656712Z [17:29:58+0000]    â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â” 121.1/121.1 kB 3.0 MB/s eta 0:00:00
2024-04-28T17:30:16.4130955Z [17:29:58+0000] Downloading whitenoise-6.6.0-py3-none-any.whl (19 kB)
2024-04-28T17:30:16.4432626Z [17:29:59+0000] Installing collected packages: whitenoise, urllib3, tzdata, typing_extensions, sqlparse, six, python-dotenv, idna, charset-normalizer, certifi, asgiref, requests, isodate, Django, azure-core, azure-servicebus
2024-04-28T17:30:16.4846768Z [17:30:12+0000] Successfully installed Django-5.0.4 asgiref-3.8.1 azure-core-1.30.1 azure-servicebus-7.12.1 certifi-2024.2.2 charset-normalizer-3.3.2 idna-3.7 isodate-0.6.1 python-dotenv-1.0.1 requests-2.31.0 six-1.16.0 sqlparse-0.5.0 typing_extensions-4.11.0 tzdata-2024.1 urllib3-2.2.1 whitenoise-6.6.0
2024-04-28T17:30:16.5160239Z 
2024-04-28T17:30:16.5370248Z Content in source directory is a Django app
2024-04-28T17:30:16.5961724Z Running collectstatic...
2024-04-28T17:31:25  No new trace in the past 1 min(s).

.
.

2024-04-28T18:09:13.4648221Z Exception Message : Deployment failed
2024-04-28T18:09:13.4877435Z Exception StackTrace :    at Kudu.Core.Deployment.DeploymentManager.DeployAsync(IRepository repository, ChangeSet changeSet, String deployer, Boolean clean, DeploymentInfoBase deploymentInfo, Boolean needFileUpdate, Boolean fullBuildByDefault) in /tmp/KuduLite/Kudu.Core/Deployment/DeploymentManager.cs:line 307
2024-04-28T18:09:13.4889736Z    at Kudu.Core.Deployment.FetchDeploymentManager.PerformDeployment(DeploymentInfoBase deploymentInfo, IDisposable tempDeployment, ChangeSet tempChangeSet, DeployStatusApiResult updateStatusObj) in /tmp/KuduLite/Kudu.Core/Deployment/FetchDeploymentManager.cs:line 258
2024-04-28T18:09:13.4931808Z    at Kudu.Core.Deployment.FetchDeploymentManager.PerformDeployment(DeploymentInfoBase deploymentInfo, IDisposable tempDeployment, ChangeSet tempChangeSet, DeployStatusApiResult updateStatusObj) in /tmp/KuduLite/Kudu.Core/Deployment/FetchDeploymentManager.cs:line 304
2024-04-28T18:09:13.5012115Z    at Kudu.Core.Deployment.FetchDeploymentManager.<>c__DisplayClass10_0.<<FetchDeploy>b__0>d.MoveNext() in /tmp/KuduLite/Kudu.Core/Deployment/FetchDeploymentManager.cs:line 148
2024-04-28T18:09:13.5030826Z --- End of stack trace from previous location ---
2024-04-28T18:09:13.5115844Z    at Kudu.Core.Deployment.FetchDeploymentManager.FetchDeploy(DeploymentInfoBase deployInfo, Boolean asyncRequested, Uri requestUri, String targetBranch) in /tmp/KuduLite/Kudu.Core/Deployment/FetchDeploymentManager.cs:line 141
2024-04-28T18:09:13.5128825Z    at Kudu.Services.Deployment.PushDeploymentController.PushDeployAsync(ArtifactDeploymentInfo deploymentInfo, Boolean isAsync, HttpContext context, JObject requestJson) in /tmp/KuduLite/Kudu.Services/Deployment/PushDeploymentController.cs:line 788
2024-04-28T18:09:13.5203420Z    at Kudu.Services.Deployment.PushDeploymentController.OneDeploy(String type, Boolean async, String path, Nullable`1 restart, Nullable`1 clean, Boolean ignoreStack, Boolean trackDeploymentProgress, Boolean trackStatus, Boolean reset) in /tmp/KuduLite/Kudu.Services/Deployment/PushDeploymentController.cs:line 614
2024-04-28T18:09:13.5212018Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
2024-04-28T18:09:13.5218292Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
2024-04-28T18:09:13.5223634Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
2024-04-28T18:09:13.5508959Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
2024-04-28T18:09:13.5520607Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
2024-04-28T18:09:13.5537851Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
2024-04-28T18:09:13.5621747Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
2024-04-28T18:09:13.5812886Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
2024-04-28T18:09:13.5822430Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
2024-04-28T18:09:13.5830562Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
2024-04-28T18:09:13.5836860Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
2024-04-28T18:09:13.5844025Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
2024-04-28T18:09:13.5939699Z    at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
2024-04-28T18:09:13.6047504Z    at Kudu.Services.Web.Tracing.TraceMiddleware.Invoke(HttpContext context) in /tmp/KuduLite/Kudu.Services.Web/Tracing/TraceMiddleware.cs:line 107
2024-04-28T18:09:13.6486006Z [41m[30mfail[39m[22m[49m: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[1]
2024-04-28T18:09:13.6523895Z       An unhandled exception has occurred while executing the request.
2024-04-28T18:09:13.6532435Z       ExitCode: 137, Output: Operation performed by Microsoft Oryx, https://github.com/Microsoft/Oryx
2024-04-28T18:09:13.6632970Z       You can report issues at https://github.com/Microsoft/Oryx/issues

```

**Comment by ravi303** [comment]
For now, I am just adding a app settings as DISABLE_COLLECTSTATIC=True and proceed but I don't have a clear understanding of why it is failing on collectstatic
