### ISSUE TITLE
Azure Function zip deployment fails with System.AggregateException when trying to download the SDK

### ISSUE THREAD

**Issue by tcdejong** [microsoft/Oryx#2527]
### Bug Report

- At what date and time did you most recently experience the problem?
  - Today, 2024-09-26 13:30 CEST (UTC+2)

- Where did you experience the problem? E.g. Azure Web Apps, Azure Functions, Azure Container Registry, or offline use.

  - Azure Function zip deployment from VS Code
  - The function is a Python 3.11 function with several http triggers

- If your repo is publicly available please share its URL:

  - Private repo

- What happened?

  - Oryx fails during the zip-deployment.  
  - It worked fine three days earlier. 
  - No known configuration changes occured in the meantime. 
  - The log below says a http request failed. 
    - The Oryx error appears in the 'detecting platforms' step. 
    - Successful deployments would detect the platform as python 3.11.8 correctly and proceed from there. 
    - It says a http request failed to retrieve the oryx sdk, but given that there are no configuration changes I don't know why this would fail now while it previously succeeded. 

- What did you expect or want to happen?

  - The deployment to succeed as always

- How can we reproduce it?

  - Unfortunately I do not know. I haven't been able to make an MVP yet.

- Do you have log output? Please include between the backticks:

Failed deployment, 2024-09-26 13:33 UTC+2:

```
1:33:45 PM VBN-WE-D-AF-DITMatching: Starting deployment...
1:33:45 PM VBN-WE-D-AF-DITMatching: Creating zip package...
1:33:45 PM VBN-WE-D-AF-DITMatching: Adding 12 files to zip package...
[Files redacted]
1:33:45 PM VBN-WE-D-AF-DITMatching: Zip package size: 38.1 kB
1:33:43 PM VBN-WE-D-AF-DITMatching: Fetching changes.
1:33:44 PM VBN-WE-D-AF-DITMatching: Cleaning up temp folders from previous zip deployments and extracting pushed zip file /tmp/zipdeploy/eca4a994-d201-455c-9d1c-518a323d5be8.zip (0.04 MB) to /tmp/zipdeploy/extracted
1:33:46 PM VBN-WE-D-AF-DITMatching: Updating submodules.
1:33:47 PM VBN-WE-D-AF-DITMatching: Preparing deployment for commit id '47e7bfda-5'.
1:33:47 PM VBN-WE-D-AF-DITMatching: PreDeployment: context.CleanOutputPath False
1:33:47 PM VBN-WE-D-AF-DITMatching: PreDeployment: context.OutputPath /home/site/wwwroot
1:33:47 PM VBN-WE-D-AF-DITMatching: Repository path is /tmp/zipdeploy/extracted
1:33:47 PM VBN-WE-D-AF-DITMatching: Running oryx build...
1:33:47 PM VBN-WE-D-AF-DITMatching: Command: oryx build /tmp/zipdeploy/extracted -o /home/site/wwwroot --platform python --platform-version 3.11 -p packagedir=.python_packages/lib/site-packages
1:33:48 PM VBN-WE-D-AF-DITMatching: Operation performed by Microsoft Oryx, https://github.com/Microsoft/Oryx
1:33:48 PM VBN-WE-D-AF-DITMatching: You can report issues at https://github.com/Microsoft/Oryx/issues
1:33:48 PM VBN-WE-D-AF-DITMatching: Oryx Version: 0.2.20230210.1, Commit: a49c8f6b8abbe95b4356552c4c884dea7fd0d86e, ReleaseTagName: 20230210.1
1:33:48 PM VBN-WE-D-AF-DITMatching: Build Operation ID: 8c0249613e258690
1:33:48 PM VBN-WE-D-AF-DITMatching: Repository Commit : 47e7bfda-5171-49f1-96c0-e6409f7ed915
1:33:48 PM VBN-WE-D-AF-DITMatching: OS Type           : bullseye
1:33:48 PM VBN-WE-D-AF-DITMatching: Image Type        : githubactions
1:33:48 PM VBN-WE-D-AF-DITMatching: Detecting platforms...
1:35:28 PM VBN-WE-D-AF-DITMatching: Error: Oops... An unexpected error has occurred.
1:35:28 PM VBN-WE-D-AF-DITMatching: Error: System.AggregateException: Http request to retrieve the SDKs available to download from 'https://oryx-cdn.microsoft.io' failed. Please ensure that your network configuration allows traffic to required Oryx dependencies, as documented in 'https://github.com/microsoft/Oryx/blob/main/doc/hosts/appservice.md#network-dependencies'
1:35:28 PM VBN-WE-D-AF-DITMatching: System.AggregateException: One or more errors occurred. (A task was canceled.)
1:35:28 PM VBN-WE-D-AF-DITMatching:  ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
1:35:28 PM VBN-WE-D-AF-DITMatching:    --- End of inner exception stack trace ---
1:35:28 PM VBN-WE-D-AF-DITMatching:    at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
1:35:28 PM VBN-WE-D-AF-DITMatching:    at System.Threading.Tasks.Task`1.get_Result()
1:35:28 PM VBN-WE-D-AF-DITMatching:    at Microsoft.Oryx.BuildScriptGenerator.ListBlobsHelper.GetAllBlobs(String sdkStorageBaseUrl, String platform, HttpClient httpClient, String oryxSdkStorageAccountAccessToken) in /usr/oryx/src/BuildScriptGenerator/Helpers/ListBlobsHelper.cs:line 23
1:35:28 PM VBN-WE-D-AF-DITMatching:    at Microsoft.Oryx.BuildScriptGenerator.ListBlobsHelper.GetAllBlobs(String sdkStorageBaseUrl, String platform, HttpClient httpClient, String oryxSdkStorageAccountAccessToken) in /usr/oryx/src/BuildScriptGenerator/Helpers/ListBlobsHelper.cs:line 29
1:35:28 PM VBN-WE-D-AF-DITMatching:    at Microsoft.Oryx.BuildScriptGenerator.SdkStorageVersionProviderBase.GetAvailableVersionsFromStorage(String platformName) in /usr/oryx/src/BuildScriptGenerator/SdkStorageVersionProviderBase.cs:line 55
1:35:28 PM VBN-WE-D-AF-DITMatching:    at Microsoft.Oryx.BuildScriptGenerator.Python.PythonSdkStorageVersionProvider.GetVersionInfo() in /usr/oryx/src/BuildScriptGenerator/Python/VersionProviders/PythonSdkStorageVersionProvider.cs:line 25
1:35:28 PM VBN-WE-D-AF-DITMatching:    at Microsoft.Oryx.BuildScriptGenerator.Python.PythonVersionProvider.GetVersionInfo() in /usr/oryx/src/BuildScriptGenerator/Python/VersionProviders/PythonVersionProvider.cs:line 44
1:35:28 PM VBN-WE-D-AF-DITMatching:    at Microsoft.Oryx.BuildScriptGenerator.Python.PythonPlatform.get_SupportedVersions() in /usr/oryx/src/BuildScriptGenerator/Python/PythonPlatform.cs:line 117
1:35:28 PM VBN-WE-D-AF-DITMatching:    at Microsoft.Oryx.BuildScriptGenerator.Python.PythonPlatform.GetMaxSatisfyingVersionAndVerify(String version) in /usr/oryx/src/BuildScriptGenerator/Python/PythonPlatform.cs:line 631
1:35:28 PM VBN-WE-D-AF-DITMatching:    at Microsoft.Oryx.BuildScriptGenerator.Python.PythonPlatform.ResolveVersions(RepositoryContext context, PlatformDetectorResult detectorResult) in /usr/oryx/src/BuildScriptGenerator/Python/PythonPlatform.cs:line 401
1:35:28 PM VBN-WE-D-AF-DITMatching:    at Microsoft.Oryx.BuildScriptGenerator.Python.PythonPlatform.Detect(RepositoryContext context) in /usr/oryx/src/BuildScriptGenerator/Python/PythonPlatform.cs:line 136
1:35:28 PM VBN-WE-D-AF-DITMatching:    at Microsoft.Oryx.BuildScriptGenerator.DefaultPlatformsInformationProvider.GetPlatformsInfo(RepositoryContext context) in /usr/oryx/src/BuildScriptGenerator/DefaultPlatformsInformationProvider.cs:line 53
1:35:28 PM VBN-WE-D-AF-DITMatching:    at Microsoft.Oryx.BuildScriptGenerator.DefaultBuildScriptGenerator.GenerateBashScript(BuildScriptGeneratorContext context, String& script, List`1 checkerMessageSink) in /usr/oryx/src/BuildScriptGenerator/DefaultBuildScriptGenerator.cs:line 70
1:35:28 PM VBN-WE-D-AF-DITMatching:    at Microsoft.Oryx.BuildScriptGeneratorCli.BuildScriptGenerator.TryGenerateScript(String& generatedScript, Exception& exception) in /usr/oryx/src/BuildScriptGeneratorCli/BuildScriptGenerator.cs:line 65
1:35:28 PM VBN-WE-D-AF-DITMatching:    at Microsoft.Oryx.BuildScriptGeneratorCli.BuildCommand.Execute(IServiceProvider serviceProvider, IConsole console) in /usr/oryx/src/BuildScriptGeneratorCli/Commands/BuildCommand.cs:line 182
1:35:28 PM VBN-WE-D-AF-DITMatching:    at Microsoft.Oryx.BuildScriptGeneratorCli.CommandBase.OnExecute(CommandLineApplication app, IConsole console) in /usr/oryx/src/BuildScriptGeneratorCli/Commands/CommandBase.cs:line 88
1:35:52 PM VBN-WE-D-AF-DITMatching: Deployment failed.
```

Succesful deployment,  2024-09-23 15:18 UTC+2:

```
3:18:42 PM VBN-WE-D-AF-DITMatching: Starting deployment...
3:18:42 PM VBN-WE-D-AF-DITMatching: Creating zip package...
3:18:42 PM VBN-WE-D-AF-DITMatching: Adding 11 files to zip package...
[Filenames redacted]
3:18:42 PM VBN-WE-D-AF-DITMatching: Zip package size: 36.2 kB
3:18:37 PM VBN-WE-D-AF-DITMatching: Fetching changes.
3:18:38 PM VBN-WE-D-AF-DITMatching: Cleaning up temp folders from previous zip deployments and extracting pushed zip file /tmp/zipdeploy/4a451a72-eb32-4846-990b-67a970c383ca.zip (0.03 MB) to /tmp/zipdeploy/extracted
3:18:40 PM VBN-WE-D-AF-DITMatching: Updating submodules.
3:18:41 PM VBN-WE-D-AF-DITMatching: Preparing deployment for commit id '0ba15336-0'.
3:18:41 PM VBN-WE-D-AF-DITMatching: PreDeployment: context.CleanOutputPath False
3:18:41 PM VBN-WE-D-AF-DITMatching: PreDeployment: context.OutputPath /home/site/wwwroot
3:18:41 PM VBN-WE-D-AF-DITMatching: Repository path is /tmp/zipdeploy/extracted
3:18:41 PM VBN-WE-D-AF-DITMatching: Running oryx build...
3:18:41 PM VBN-WE-D-AF-DITMatching: Command: oryx build /tmp/zipdeploy/extracted -o /home/site/wwwroot --platform python --platform-version 3.11 -p packagedir=.python_packages/lib/site-packages
3:18:42 PM VBN-WE-D-AF-DITMatching: Operation performed by Microsoft Oryx, https://github.com/Microsoft/Oryx
3:18:42 PM VBN-WE-D-AF-DITMatching: You can report issues at https://github.com/Microsoft/Oryx/issues
3:18:42 PM VBN-WE-D-AF-DITMatching: Oryx Version: 0.2.20230210.1, Commit: a49c8f6b8abbe95b4356552c4c884dea7fd0d86e, ReleaseTagName: 20230210.1
3:18:42 PM VBN-WE-D-AF-DITMatching: Build Operation ID: 3aafd4a0fff06748
3:18:42 PM VBN-WE-D-AF-DITMatching: Repository Commit : 0ba15336-0918-4e5f-86d1-9cca43db5d77
3:18:42 PM VBN-WE-D-AF-DITMatching: OS Type           : bullseye
3:18:42 PM VBN-WE-D-AF-DITMatching: Image Type        : githubactions
3:18:42 PM VBN-WE-D-AF-DITMatching: Detecting platforms...
3:18:45 PM VBN-WE-D-AF-DITMatching: Detected following platforms:
3:18:45 PM VBN-WE-D-AF-DITMatching:   python: 3.11.8
3:18:45 PM VBN-WE-D-AF-DITMatching: Version '3.11.8' of platform 'python' is not installed. Generating script to install it...
3:18:45 PM VBN-WE-D-AF-DITMatching: Source directory     : /tmp/zipdeploy/extracted
3:18:45 PM VBN-WE-D-AF-DITMatching: Destination directory: /home/site/wwwroot
3:18:46 PM VBN-WE-D-AF-DITMatching: Downloading and extracting 'python' version '3.11.8' to '/tmp/oryx/platforms/python/3.11.8'...
3:18:46 PM VBN-WE-D-AF-DITMatching: Detected image debian flavor: bullseye.
3:18:47 PM VBN-WE-D-AF-DITMatching: Downloaded in 2 sec(s).
3:18:47 PM VBN-WE-D-AF-DITMatching: Verifying checksum...
3:18:47 PM VBN-WE-D-AF-DITMatching: Extracting contents...
3:18:53 PM VBN-WE-D-AF-DITMatching: performing sha512 checksum for: python...
3:18:53 PM VBN-WE-D-AF-DITMatching: Done in 8 sec(s).
3:18:53 PM VBN-WE-D-AF-DITMatching: image detector file exists, platform is python..
3:18:53 PM VBN-WE-D-AF-DITMatching: OS detector file exists, OS is bullseye..
3:18:54 PM VBN-WE-D-AF-DITMatching: Python Version: /tmp/oryx/platforms/python/3.11.8/bin/python3.11
3:18:54 PM VBN-WE-D-AF-DITMatching: Creating directory for command manifest file if it does not exist
3:18:54 PM VBN-WE-D-AF-DITMatching: Removing existing manifest file
3:18:54 PM VBN-WE-D-AF-DITMatching: Running pip install...
3:19:23 PM VBN-WE-D-AF-DITMatching: Done in 29 sec(s).
3:19:23 PM VBN-WE-D-AF-DITMatching: [13:18:54+0000] Collecting azure-keyvault-secrets
3:19:23 PM VBN-WE-D-AF-DITMatching: [13:18:54+0000]   Downloading azure_keyvault_secrets-4.8.0-py3-none-any.whl (82 kB)
3:19:23 PM VBN-WE-D-AF-DITMatching: [13:18:54+0000] Collecting azure-identity
3:19:23 PM VBN-WE-D-AF-DITMatching: [13:18:54+0000]   Downloading azure_identity-1.18.0-py3-none-any.whl (187 kB)
3:19:23 PM VBN-WE-D-AF-DITMatching: [13:18:54+0000] Collecting azure-functions
3:19:23 PM VBN-WE-D-AF-DITMatching: [13:18:54+0000]   Downloading azure_functions-1.20.0-py3-none-any.whl (181 kB)
3:19:23 PM VBN-WE-D-AF-DITMatching: [13:18:55+0000] Collecting msal
3:19:23 PM VBN-WE-D-AF-DITMatching: [13:18:55+0000]   Downloading msal-1.31.0-py3-none-any.whl (113 kB)
3:19:23 PM VBN-WE-D-AF-DITMatching: [13:18:55+0000] Collecting jarowinkler
3:19:23 PM VBN-WE-D-AF-DITMatching: [13:18:55+0000]   Downloading jarowinkler-2.0.1-py3-none-any.whl (5.6 kB)
3:19:23 PM VBN-WE-D-AF-DITMatching: [13:18:55+0000] Collecting unidecode
3:19:23 PM VBN-WE-D-AF-DITMatching: [13:18:55+0000]   Downloading Unidecode-1.3.8-py3-none-any.whl (235 kB)
3:19:23 PM VBN-WE-D-AF-DITMatching: [13:18:56+0000] Collecting pandas
3:19:23 PM VBN-WE-D-AF-DITMatching: [13:18:56+0000]   Downloading pandas-2.2.3-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (13.1 MB)
3:19:23 PM VBN-WE-D-AF-DITMatching: [13:18:57+0000] Collecting python-dotenv
3:19:23 PM VBN-WE-D-AF-DITMatching: [13:18:57+0000]   Downloading python_dotenv-1.0.1-py3-none-any.whl (19 kB)
3:19:23 PM VBN-WE-D-AF-DITMatching: [13:18:57+0000] Collecting isodate>=0.6.1
3:19:23 PM VBN-WE-D-AF-DITMatching: [13:18:57+0000]   Downloading isodate-0.6.1-py2.py3-none-any.whl (41 kB)
3:19:23 PM VBN-WE-D-AF-DITMatching: [13:18:57+0000] Collecting typing-extensions>=4.0.1
3:19:23 PM VBN-WE-D-AF-DITMatching: [13:18:57+0000]   Downloading typing_extensions-4.12.2-py3-none-any.whl (37 kB)
3:19:23 PM VBN-WE-D-AF-DITMatching: [13:18:57+0000] Collecting azure-core<2.0.0,>=1.29.5
3:19:23 PM VBN-WE-D-AF-DITMatching: [13:18:57+0000]   Downloading azure_core-1.31.0-py3-none-any.whl (197 kB)
3:19:23 PM VBN-WE-D-AF-DITMatching: [13:18:57+0000] Collecting msal-extensions>=1.2.0
3:19:23 PM VBN-WE-D-AF-DITMatching: [13:18:57+0000]   Downloading msal_extensions-1.2.0-py3-none-any.whl (19 kB)
3:19:23 PM VBN-WE-D-AF-DITMatching: [13:18:59+0000] Collecting cryptography>=2.5
3:19:23 PM VBN-WE-D-AF-DITMatching: [13:18:59+0000]   Downloading cryptography-43.0.1-cp39-abi3-manylinux_2_28_x86_64.whl (4.0 MB)
3:19:23 PM VBN-WE-D-AF-DITMatching: [13:18:59+0000] Collecting requests<3,>=2.0.0
3:19:23 PM VBN-WE-D-AF-DITMatching: [13:18:59+0000]   Downloading requests-2.32.3-py3-none-any.whl (64 kB)
3:19:23 PM VBN-WE-D-AF-DITMatching: [13:18:59+0000] Collecting PyJWT[crypto]<3,>=1.0.0
3:19:23 PM VBN-WE-D-AF-DITMatching: [13:18:59+0000]   Downloading PyJWT-2.9.0-py3-none-any.whl (22 kB)
3:19:23 PM VBN-WE-D-AF-DITMatching: [13:19:03+0000] Collecting rapidfuzz<4.0.0,>=3.5.2
3:19:23 PM VBN-WE-D-AF-DITMatching: [13:19:03+0000]   Downloading rapidfuzz-3.10.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.1 MB)
3:19:23 PM VBN-WE-D-AF-DITMatching: [13:19:03+0000] Collecting python-dateutil>=2.8.2
3:19:23 PM VBN-WE-D-AF-DITMatching: [13:19:03+0000]   Downloading python_dateutil-2.9.0.post0-py2.py3-none-any.whl (229 kB)
3:19:23 PM VBN-WE-D-AF-DITMatching: [13:19:04+0000] Collecting tzdata>=2022.7
3:19:23 PM VBN-WE-D-AF-DITMatching: [13:19:04+0000]   Downloading tzdata-2024.1-py2.py3-none-any.whl (345 kB)
3:19:23 PM VBN-WE-D-AF-DITMatching: [13:19:05+0000] Collecting numpy>=1.23.2
3:19:23 PM VBN-WE-D-AF-DITMatching: [13:19:05+0000]   Downloading numpy-2.1.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (16.3 MB)
3:19:23 PM VBN-WE-D-AF-DITMatching: [13:19:05+0000] Collecting pytz>=2020.1
3:19:23 PM VBN-WE-D-AF-DITMatching: [13:19:05+0000]   Downloading pytz-2024.2-py2.py3-none-any.whl (508 kB)
3:19:23 PM VBN-WE-D-AF-DITMatching: [13:19:05+0000] Collecting six>=1.11.0
3:19:23 PM VBN-WE-D-AF-DITMatching: [13:19:05+0000]   Downloading six-1.16.0-py2.py3-none-any.whl (11 kB)
3:19:23 PM VBN-WE-D-AF-DITMatching: [13:19:06+0000] Collecting cffi>=1.12
3:19:23 PM VBN-WE-D-AF-DITMatching: [13:19:06+0000]   Downloading cffi-1.17.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (467 kB)
3:19:23 PM VBN-WE-D-AF-DITMatching: [13:19:06+0000] Collecting pycparser
3:19:23 PM VBN-WE-D-AF-DITMatching: [13:19:06+0000]   Downloading pycparser-2.22-py3-none-any.whl (117 kB)
3:19:23 PM VBN-WE-D-AF-DITMatching: [13:19:06+0000] Collecting portalocker<3,>=1.4
3:19:23 PM VBN-WE-D-AF-DITMatching: [13:19:06+0000]   Downloading portalocker-2.10.1-py3-none-any.whl (18 kB)
3:19:23 PM VBN-WE-D-AF-DITMatching: [13:19:06+0000] Collecting urllib3<3,>=1.21.1
3:19:23 PM VBN-WE-D-AF-DITMatching: [13:19:06+0000]   Downloading urllib3-2.2.3-py3-none-any.whl (126 kB)
3:19:23 PM VBN-WE-D-AF-DITMatching: [13:19:07+0000] Collecting idna<4,>=2.5
3:19:23 PM VBN-WE-D-AF-DITMatching: [13:19:07+0000]   Downloading idna-3.10-py3-none-any.whl (70 kB)
3:19:23 PM VBN-WE-D-AF-DITMatching: [13:19:07+0000] Collecting charset-normalizer<4,>=2
3:19:23 PM VBN-WE-D-AF-DITMatching: [13:19:07+0000]   Downloading charset_normalizer-3.3.2-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (140 kB)
3:19:23 PM VBN-WE-D-AF-DITMatching: [13:19:07+0000] Collecting certifi>=2017.4.17
3:19:23 PM VBN-WE-D-AF-DITMatching: [13:19:07+0000]   Downloading certifi-2024.8.30-py3-none-any.whl (167 kB)
3:19:23 PM VBN-WE-D-AF-DITMatching: [13:19:08+0000] Installing collected packages: pycparser, cffi, urllib3, PyJWT, idna, cryptography, charset-normalizer, certifi, requests, typing-extensions, six, portalocker, msal, tzdata, rapidfuzz, pytz, python-dateutil, numpy, msal-extensions, isodate, azure-core, unidecode, python-dotenv, pandas, jarowinkler, azure-keyvault-secrets, azure-identity, azure-functions
3:19:23 PM VBN-WE-D-AF-DITMatching: [13:19:23+0000] Successfully installed PyJWT-2.9.0 azure-core-1.31.0 azure-functions-1.20.0 azure-identity-1.18.0 azure-keyvault-secrets-4.8.0 certifi-2024.8.30 cffi-1.17.1 charset-normalizer-3.3.2 cryptography-43.0.1 idna-3.10 isodate-0.6.1 jarowinkler-2.0.1 msal-1.31.0 msal-extensions-1.2.0 numpy-2.1.1 pandas-2.2.3 portalocker-2.10.1 pycparser-2.22 python-dateutil-2.9.0.post0 python-dotenv-1.0.1 pytz-2024.2 rapidfuzz-3.10.0 requests-2.32.3 six-1.16.0 typing-extensions-4.12.2 tzdata-2024.1 unidecode-1.3.8 urllib3-2.2.3
3:19:23 PM VBN-WE-D-AF-DITMatching: WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
3:19:23 PM VBN-WE-D-AF-DITMatching: WARNING: You are using pip version 21.2.4; however, version 24.2 is available.
3:19:23 PM VBN-WE-D-AF-DITMatching: You should consider upgrading via the '/tmp/oryx/platforms/python/3.11.8/bin/python3.11 -m pip install --upgrade pip' command.
3:19:24 PM VBN-WE-D-AF-DITMatching: Not a vso image, so not writing build commands
3:19:24 PM VBN-WE-D-AF-DITMatching: Preparing output...
3:19:24 PM VBN-WE-D-AF-DITMatching: Copying files to destination directory '/home/site/wwwroot'...
3:19:26 PM VBN-WE-D-AF-DITMatching: Done in 2 sec(s).
3:19:26 PM VBN-WE-D-AF-DITMatching: Removing existing manifest file
3:19:26 PM VBN-WE-D-AF-DITMatching: Creating a manifest file...
3:19:26 PM VBN-WE-D-AF-DITMatching: Manifest file created.
3:19:26 PM VBN-WE-D-AF-DITMatching: Copying .ostype to manifest output directory.
3:19:26 PM VBN-WE-D-AF-DITMatching: Done in 41 sec(s).
3:19:26 PM VBN-WE-D-AF-DITMatching: Running post deployment command(s)...
3:19:26 PM VBN-WE-D-AF-DITMatching: Generating summary of Oryx build
3:19:26 PM VBN-WE-D-AF-DITMatching: Deployment Log file does not exist in /tmp/oryx-build.log
3:19:26 PM VBN-WE-D-AF-DITMatching: The logfile at /tmp/oryx-build.log is empty. Unable to fetch the summary of build
3:19:26 PM VBN-WE-D-AF-DITMatching: Triggering recycle (preview mode disabled).
3:19:26 PM VBN-WE-D-AF-DITMatching: Linux Consumption plan has a 1.5 GB memory limit on a remote build container.
3:19:26 PM VBN-WE-D-AF-DITMatching: To check our service limit, please visit https://docs.microsoft.com/en-us/azure/azure-functions/functions-scale#service-limits
3:19:26 PM VBN-WE-D-AF-DITMatching: Writing the artifacts to a squashfs file
3:19:30 PM VBN-WE-D-AF-DITMatching: Parallel mksquashfs: Using 1 processor
3:19:30 PM VBN-WE-D-AF-DITMatching: Creating 4.0 filesystem on /home/site/artifacts/functionappartifact.squashfs, block size 131072.
3:20:05 PM VBN-WE-D-AF-DITMatching: [======-                                                       ]  800/8029   9%
3:20:06 PM VBN-WE-D-AF-DITMatching: [=============================================================|] 8029/8029 100%
3:20:06 PM VBN-WE-D-AF-DITMatching: Exportable Squashfs 4.0 filesystem, gzip compressed, data block size 131072
3:20:06 PM VBN-WE-D-AF-DITMatching: 	compressed data, compressed metadata, compressed fragments,
3:20:06 PM VBN-WE-D-AF-DITMatching: 	compressed xattrs, compressed ids
3:20:06 PM VBN-WE-D-AF-DITMatching: 	duplicates are removed
3:20:06 PM VBN-WE-D-AF-DITMatching: Filesystem size 54522.58 Kbytes (53.24 Mbytes)
3:20:06 PM VBN-WE-D-AF-DITMatching: 	30.01% of uncompressed filesystem size (181657.22 Kbytes)
3:20:06 PM VBN-WE-D-AF-DITMatching: Inode table size 74747 bytes (73.00 Kbytes)
3:20:06 PM VBN-WE-D-AF-DITMatching: 	28.30% of uncompressed inode table size (264082 bytes)
3:20:06 PM VBN-WE-D-AF-DITMatching: Directory table size 77284 bytes (75.47 Kbytes)
3:20:06 PM VBN-WE-D-AF-DITMatching: 	36.46% of uncompressed directory table size (211967 bytes)
3:20:06 PM VBN-WE-D-AF-DITMatching: Number of duplicate files found 724
3:20:06 PM VBN-WE-D-AF-DITMatching: Number of inodes 8137
3:20:06 PM VBN-WE-D-AF-DITMatching: Number of files 7432
3:20:06 PM VBN-WE-D-AF-DITMatching: Number of fragments 703
3:20:06 PM VBN-WE-D-AF-DITMatching: Number of symbolic links  0
3:20:06 PM VBN-WE-D-AF-DITMatching: Number of device nodes 0
3:20:06 PM VBN-WE-D-AF-DITMatching: Number of fifo nodes 0
3:20:06 PM VBN-WE-D-AF-DITMatching: Number of socket nodes 0
3:20:06 PM VBN-WE-D-AF-DITMatching: Number of directories 705
3:20:06 PM VBN-WE-D-AF-DITMatching: Number of ids (unique uids + gids) 1
3:20:06 PM VBN-WE-D-AF-DITMatching: Number of uids 1
3:20:06 PM VBN-WE-D-AF-DITMatching: 	root (0)
3:20:06 PM VBN-WE-D-AF-DITMatching: Number of gids 1
3:20:06 PM VBN-WE-D-AF-DITMatching: 	root (0)
3:20:06 PM VBN-WE-D-AF-DITMatching: Creating placeholder blob for linux consumption function app...
3:20:07 PM VBN-WE-D-AF-DITMatching: SCM_RUN_FROM_PACKAGE placeholder blob scm-latest-VBN-WE-D-AF-DITMatching.zip located
3:20:07 PM VBN-WE-D-AF-DITMatching: Uploading built content /home/site/artifacts/functionappartifact.squashfs for linux consumption function app...
3:20:09 PM VBN-WE-D-AF-DITMatching: Resetting all workers for vbn-we-d-af-ditmatching.azurewebsites.net
3:20:09 PM VBN-WE-D-AF-DITMatching: Deployment successful. deployer = ms-azuretools-vscode deploymentPath = Functions App ZipDeploy. Extract zip. Remote build.
3:20:27 PM VBN-WE-D-AF-DITMatching: Syncing triggers...
3:20:36 PM VBN-WE-D-AF-DITMatching: Querying triggers...
3:20:37 PM VBN-WE-D-AF-DITMatching: WARNING: Some http trigger urls cannot be displayed in the output window because they require an authentication token. Instead, you may copy them from the Azure Functions explorer.
```

**Comment by tcdejong** [comment]
The obvious step would be to follow the link to [the documentation](https://github.com/microsoft/Oryx/blob/main/doc/hosts/appservice.md#network-dependencies) about the network requirements, which I did, but I don't see any reason the traffic would be blocked.

**Comment by tcdejong** [comment]
Magically resolved without any changes on my part. Closing the issue, but the underlying issue is probably still there.
