### ISSUE TITLE
When an aspnet core application fails to start a core dump is generated, but i can't find it

### ISSUE THREAD

**Issue by valeriob** [microsoft/Oryx#358]
We have a running aspnet core 2.2 application in azure web apps from many months.
Last week we found this problem, the web application looks like running from the azure console, but if we browse to it's url we see the default azure webapp application.
If we stop and start the application again everything works again for a few days.
I would like to know why the system runs the default application on a crash instead of restarting it ?
Why suddenly (we did not update the web app) the Microsoft.Diagnostics.Tracing.EventPipeEventSource throws null reference exception ?

The log is below, i would like to diagnose the problem with the core dump, but i can't find where it is : 

2019-09-19T05:02:14.002632974Z Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
2019-09-19T05:02:14.002639674Z    at Microsoft.Diagnostics.Tracing.EventPipeEventSource.Dispose(Boolean disposing)
2019-09-19T05:02:14.002643875Z    at Microsoft.Diagnostics.Tracing.TraceEventDispatcher.Finalize()
2019-09-19T05:02:14.382141146Z /opt/startup/startup.sh: line 11:    27 Aborted                 **(core dumped)** dotnet /home/site/wwwroot/OnTms.Amadori.Consegne.Web.dll
2019-09-19T05:02:14.385321481Z WARNING: Startup command execution failed with exit code 134
2019-09-19T05:02:14.385821287Z Running the default application instead...
2019-09-19T05:02:14.882893751Z Hosting environment: Development
2019-09-19T05:02:14.887639803Z Content root path: /defaulthome/hostingstart/
2019-09-19T05:02:14.888119909Z Now listening on: http://[::]:8080
2019-09-19T05:02:14.888530113Z Application started. Press Ctrl+C to shut down.

Thanks
Valerio

**Comment by kichalla** [comment]
Thanks @valeriob. Since you would have access to the runtime container, have you tried to see if coredump was enabled or not and if not have you tried enabling it and see? https://linux-audit.com/understand-and-configure-core-dumps-work-on-linux/

I am in touch with another team about your question and will keep you posted.

**Comment by valeriob** [comment]
Thanks @kichalla, i'm doing code deployment and i did not know i could access the runtime container nor if it's enabled in the default aspnet core 2.2 images.

**Comment by kichalla** [comment]
@valeriob FYI, currently it is not possible to capture the dumps in AppService since that capability is not built-in yet.

**Comment by valeriob** [comment]
Thanks @kichalla if you have an issue i can subscribe to let me know.
