### ISSUE TITLE
Azure Function App (python HttpTrigger) failed to publish with fbprophet 

### ISSUE THREAD

**Issue by QEDHamburg** [microsoft/Oryx#541]
### Bug Report

- At what date and time did you most recently experience the problem?
Today, at 4:30 pm

- Where did you experience the problem? E.g. Azure Web Apps, Azure Functions, Azure Container Registry, or offline use.

Azure Functions

- If your repo is publicly available please share its URL:
No, but it's the standard template from the Azure Functions HttpTrigger in Python with the following requirements.txt:

azure-functions
pandas
numpy
fbprophet

- What happened?

The process wasn't able to build fbprophet.

- What did you expect or want to happen?

A successful deployment, since the application runs smoothly on localhost.

- How can we reproduce it?

Get the HttpTrigger Python template for Azure Functions on Visual Studio Code, add fbprophet to the requirements.txt file and see the magic happen.

- Do you have log output? Please include between the backticks:

```
Getting site publishing info...
Creating archive for current directory...
Performing remote build for functions project.
Deleting the old .python_packages directory
Uploading 1.32 MB [###############################################################################]
Remote build in progress, please wait...
Updating submodules.
Preparing deployment for commit id '6d70d3a9c5'.
Repository path is /tmp/zipdeploy/extracted
Running oryx build...
Command: oryx build /tmp/zipdeploy/extracted -o /home/site/wwwroot --platform python --platform-version 3.7 -p packagedir=.python_packages/lib/site-packages
Build orchestrated by Microsoft Oryx, https://github.com/Microsoft/Oryx
You can report issues at https://github.com/Microsoft/Oryx/issues

Oryx Version      : 0.2.20191018.1, Commit: b56054ad55c50d02d333db35752b7f0aee706ad5, ReleaseTagName: 20191018.1
Build Operation ID: |obLdj0UdgPk=.d9879354_
Repository Commit : 6d70d3a9c5f947ee9314c2985a87c304


Source directory     : /tmp/zipdeploy/extracted
Destination directory: /home/site/wwwroot

Python Version: /opt/python/3.7.4/bin/python3

Running pip install...
[15:45:12+0000] Collecting azure-functions (from -r requirements.txt (line 1))
[15:45:13+0000]   Using cached https://files.pythonhosted.org/packages/2a/82/58337ae36e465df298f61767d6e9977c6170bc0479a99bde42ec70f460db/azure_functions-1.2.0-py3-none-any.whl
[15:45:13+0000] Collecting pandas (from -r requirements.txt (line 2))
[15:45:13+0000]   Using cached https://files.pythonhosted.org/packages/4a/6a/94b219b8ea0f2d580169e85ed1edc0163743f55aaeca8a44c2e8fc1e344e/pandas-1.0.3-cp37-cp37m-manylinux1_x86_64.whl
[15:45:14+0000] Collecting numpy (from -r requirements.txt (line 3))
[15:45:14+0000]   Using cached https://files.pythonhosted.org/packages/b7/ce/d0b92f0283faa4da76ea82587ff9da70104e81f59ba14f76c87e4196254e/numpy-1.18.2-cp37-cp37m-manylinux1_x86_64.whl
[15:45:15+0000] Collecting fbprophet (from -r requirements.txt (line 4))
[15:45:15+0000]   Using cached https://files.pythonhosted.org/packages/f7/86/4509e952f9724f084625e93e0bf8d8519b25c79029a0a916b0f996644c75/fbprophet-0.6.tar.gz
[15:45:16+0000] Collecting pytz>=2017.2 (from pandas->-r requirements.txt (line 2))
[15:45:16+0000]   Using cached https://files.pythonhosted.org/packages/e7/f9/f0b53f88060247251bf481fa6ea62cd0d25bf1b11a87888e53ce5b7c8ad2/pytz-2019.3-py2.py3-none-any.whl
[15:45:16+0000] Collecting python-dateutil>=2.6.1 (from pandas->-r requirements.txt (line 2))
[15:45:16+0000]   Using cached https://files.pythonhosted.org/packages/d4/70/d60450c3dd48ef87586924207ae8907090de0b306af2bce5d134d78615cb/python_dateutil-2.8.1-py2.py3-none-any.whl
[15:45:16+0000] Collecting Cython>=0.22 (from fbprophet->-r requirements.txt (line 4))
[15:45:17+0000]   Using cached https://files.pythonhosted.org/packages/7c/60/eb015186ab458f2923ae1713f5f2bb167bd6ca85b8138233f918582cdbc6/Cython-0.29.16-cp37-cp37m-manylinux1_x86_64.whl
[15:45:17+0000] Collecting cmdstanpy==0.4 (from fbprophet->-r requirements.txt (line 4))
[15:45:17+0000]   Using cached https://files.pythonhosted.org/packages/e3/a7/6d045520e6ad11cf630b483f02a0645e743fcc7f75c28fd344c769100203/cmdstanpy-0.4.0-py3-none-any.whl
[15:45:17+0000] Collecting pystan>=2.14 (from fbprophet->-r requirements.txt (line 4))
[15:45:18+0000]   Using cached https://files.pythonhosted.org/packages/9f/cc/4e88a34a015aa7aa459220bd18429f3ac6b15c703465fc7c411989f04ccc/pystan-2.19.1.1-cp37-cp37m-manylinux1_x86_64.whl
[15:45:47+0000] Collecting matplotlib>=2.0.0 (from fbprophet->-r requirements.txt (line 4))
[15:45:47+0000]   Using cached https://files.pythonhosted.org/packages/b2/c2/71fcf957710f3ba1f09088b35776a799ba7dd95f7c2b195ec800933b276b/matplotlib-3.2.1-cp37-cp37m-manylinux1_x86_64.whl
[15:45:47+0000] Collecting LunarCalendar>=0.0.9 (from fbprophet->-r requirements.txt (line 4))
[15:45:47+0000]   Using cached https://files.pythonhosted.org/packages/ab/e0/a52ffc02395474858552ca6437226e23ad67e25fd85cb387f02e479cfe01/LunarCalendar-0.0.9-py2.py3-none-any.whl
[15:45:47+0000] Collecting convertdate>=2.1.2 (from fbprophet->-r requirements.txt (line 4))
[15:45:48+0000]   Using cached https://files.pythonhosted.org/packages/c9/f8/02a18000b0fbfd714f78aa16359796727a181e80f679682e3f62771a5c23/convertdate-2.2.0-py3-none-any.whl
[15:45:48+0000] Collecting holidays>=0.9.5 (from fbprophet->-r requirements.txt (line 4))
[15:45:48+0000] Collecting setuptools-git>=1.2 (from fbprophet->-r requirements.txt (line 4))
[15:45:48+0000]   Using cached https://files.pythonhosted.org/packages/05/97/dd99fa9c0d9627a7b3c103a00f1566d8193aca8d473884ed258cca82b06f/setuptools_git-1.2-py2.py3-none-any.whl
[15:45:48+0000] Collecting six>=1.5 (from python-dateutil>=2.6.1->pandas->-r requirements.txt (line 2))
[15:45:48+0000]   Using cached https://files.pythonhosted.org/packages/65/eb/1f97cb97bfc2390a276969c6fae16075da282f5058082d4cb10c6c5c1dba/six-1.14.0-py2.py3-none-any.whl
[15:45:48+0000] Collecting kiwisolver>=1.0.1 (from matplotlib>=2.0.0->fbprophet->-r requirements.txt (line 4))
[15:45:48+0000]   Using cached https://files.pythonhosted.org/packages/93/f8/518fb0bb89860eea6ff1b96483fbd9236d5ee991485d0f3eceff1770f654/kiwisolver-1.1.0-cp37-cp37m-manylinux1_x86_64.whl
[15:45:48+0000] Collecting cycler>=0.10 (from matplotlib>=2.0.0->fbprophet->-r requirements.txt (line 4))
[15:45:48+0000]   Using cached https://files.pythonhosted.org/packages/f7/d2/e07d3ebb2bd7af696440ce7e754c59dd546ffe1bbe732c8ab68b9c834e61/cycler-0.10.0-py2.py3-none-any.whl
[15:45:48+0000] Collecting pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 (from matplotlib>=2.0.0->fbprophet->-r requirements.txt (line 4))
[15:45:48+0000]   Using cached https://files.pythonhosted.org/packages/5d/bc/1e58593167fade7b544bfe9502a26dc860940a79ab306e651e7f13be68c2/pyparsing-2.4.6-py2.py3-none-any.whl
[15:45:48+0000] Collecting ephem>=3.7.5.3 (from LunarCalendar>=0.0.9->fbprophet->-r requirements.txt (line 4))
[15:45:48+0000]   Using cached https://files.pythonhosted.org/packages/61/5a/a1f426ed925747592d4014edc99b1218a654b07b1d9952072bc1f40bff63/ephem-3.7.7.1-cp37-cp37m-manylinux2010_x86_64.whl
[15:45:48+0000] Collecting pymeeus<=1,>=0.3.6 (from convertdate>=2.1.2->fbprophet->-r requirements.txt (line 4))
[15:45:48+0000] Collecting setuptools (from kiwisolver>=1.0.1->matplotlib>=2.0.0->fbprophet->-r requirements.txt (line 4))
[15:45:49+0000]   Using cached https://files.pythonhosted.org/packages/a0/df/635cdb901ee4a8a42ec68e480c49f85f4c59e8816effbf57d9e6ee8b3588/setuptools-46.1.3-py3-none-any.whl
[15:45:49+0000] Building wheels for collected packages: fbprophet
[15:45:49+0000]   Building wheel for fbprophet (setup.py): started
[15:45:49+0000]   Building wheel for fbprophet (setup.py): finished with status 'error'
[15:45:49+0000]   Running setup.py clean for fbprophet
  ERROR: Command errored out with exit status 1:
   command: /opt/python/3.7.4/bin/python3.7 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-54da2nm6/fbprophet/setup.py'"'"'; __file__='"'"'/tmp/pip-install-54da2nm6/fbprophet/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-bmj14ve8 --python-tag cp37
       cwd: /tmp/pip-install-54da2nm6/fbprophet/
  Complete output (40 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib
  creating build/lib/fbprophet
  creating build/lib/fbprophet/stan_model
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-54da2nm6/fbprophet/setup.py", line 148, in <module>
      """
    File "/opt/python/3.7.4/lib/python3.7/site-packages/setuptools/__init__.py", line 145, in setup
      return distutils.core.setup(**attrs)
    File "/opt/python/3.7.4/lib/python3.7/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/opt/python/3.7.4/lib/python3.7/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/opt/python/3.7.4/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/opt/python/3.7.4/lib/python3.7/site-packages/wheel/bdist_wheel.py", line 192, in run
      self.run_command('build')
    File "/opt/python/3.7.4/lib/python3.7/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/opt/python/3.7.4/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/opt/python/3.7.4/lib/python3.7/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/opt/python/3.7.4/lib/python3.7/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/opt/python/3.7.4/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/tmp/pip-install-54da2nm6/fbprophet/setup.py", line 48, in run
      build_models(target_dir)
    File "/tmp/pip-install-54da2nm6/fbprophet/setup.py", line 36, in build_models
      from fbprophet.models import StanBackendEnum
    File "/tmp/pip-install-54da2nm6/fbprophet/fbprophet/__init__.py", line 8, in <module>
      from fbprophet.forecaster import Prophet
    File "/tmp/pip-install-54da2nm6/fbprophet/fbprophet/forecaster.py", line 14, in <module>
      import numpy as np
  ModuleNotFoundError: No module named 'numpy'
  ----------------------------------------
  ERROR: Failed building wheel for fbprophet
[15:45:49+0000] Failed to build fbprophet
[15:45:50+0000] Installing collected packages: azure-functions, numpy, pytz, six, python-dateutil, pandas, Cython, cmdstanpy, pystan, setuptools, kiwisolver, cycler, pyparsing, matplotlib, ephem, LunarCalendar, pymeeus, convertdate, holidays, setuptools-git, fbprophet
[15:46:14+0000]   Running setup.py install for fbprophet: started
    ERROR: Command errored out with exit status 1:
     command: /opt/python/3.7.4/bin/python3.7 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-54da2nm6/fbprophet/setup.py'"'"'; __file__='"'"'/tmp/pip-install-54da2nm6/fbprophet/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-84z_vu2a/install-record.txt --single-version-externally-managed --compile --home=/tmp/pip-target-bwnaouac
[15:46:15+0000]     Running setup.py install for fbprophet: finished with status 'error'
         cwd: /tmp/pip-install-54da2nm6/fbprophet/
    Complete output (42 lines):
[15:46:15+0000] Cleaning up...
    running install
    running build
    running build_py
    creating build
    creating build/lib
    creating build/lib/fbprophet
    creating build/lib/fbprophet/stan_model
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-54da2nm6/fbprophet/setup.py", line 148, in <module>
        """
      File "/opt/python/3.7.4/lib/python3.7/site-packages/setuptools/__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "/opt/python/3.7.4/lib/python3.7/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/opt/python/3.7.4/lib/python3.7/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/opt/python/3.7.4/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/opt/python/3.7.4/lib/python3.7/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/opt/python/3.7.4/lib/python3.7/distutils/command/install.py", line 545, in run
        self.run_command('build')
      File "/opt/python/3.7.4/lib/python3.7/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/opt/python/3.7.4/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/opt/python/3.7.4/lib/python3.7/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/opt/python/3.7.4/lib/python3.7/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/opt/python/3.7.4/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/tmp/pip-install-54da2nm6/fbprophet/setup.py", line 48, in run
        build_models(target_dir)
      File "/tmp/pip-install-54da2nm6/fbprophet/setup.py", line 36, in build_models
        from fbprophet.models import StanBackendEnum
      File "/tmp/pip-install-54da2nm6/fbprophet/fbprophet/__init__.py", line 8, in <module>
        from fbprophet.forecaster import Prophet
      File "/tmp/pip-install-54da2nm6/fbprophet/fbprophet/forecaster.py", line 14, in <module>
        import numpy as np
    ModuleNotFoundError: No module named 'numpy'
    ----------------------------------------
ERROR: Command errored out with exit status 1: /opt/python/3.7.4/bin/python3.7 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-54da2nm6/fbprophet/setup.py'"'"'; __file__='"'"'/tmp/pip-install-54da2nm6/fbprophet/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-84z_vu2a/install-record.txt --single-version-externally-managed --compile --home=/tmp/pip-target-bwnaouac Check the logs for full command output.
WARNING: You are using pip version 19.2.3, however version 20.0.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Done in 64 sec(s).
ERROR: Command errored out with exit status 1:\n   command: /opt/python/3.7.4/bin/python3.7 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-54da2nm6/fbprophet/setup.py'"'"'; __file__='"'"'/tmp/pip-install-54da2nm6/fbprophet/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-bmj14ve8 --python-tag cp37\n       cwd: /tmp/pip-install-54da2nm6/fbprophet/\n  Complete output (40 lines):\n  running bdist_wheel\n  running build\n  running build_py\n  creating build\n  creating build/lib\n  creating build/lib/fbprophet\n  creating build/lib/fbprophet/stan_model\n  Traceback (most recent call last):\n    File "<string>", line 1, in <module>\n    File "/tmp/pip-install-54da2nm6/fbprophet/setup.py", line 148, in <module>\n      """\n    File "/opt/python/3.7.4/lib/python3.7/site-packages/setuptools/__init__.py", line 145, in setup\n      return distutils.core.setup(**attrs)\n    File "/opt/python/3.7.4/lib/python3.7/distutils/core.py", line 148, in setup\n      dist.run_commands()\n    File "/opt/python/3.7.4/lib/python3.7/distutils/dist.py", line 966, in run_commands\n      self.run_command(cmd)\n    File "/opt/python/3.7.4/lib/python3.7/distutils/dist.py", line 985, in run_command\n      cmd_obj.run()\n    File "/opt/python/3.7.4/lib/python3.7/site-packages/wheel/bdist_wheel.py", line 192, in run\n      self.run_command('build')\n    File "/opt/python/3.7.4/lib/python3.7/distutils/cmd.py", line 313, in run_command\n      self.distribution.run_command(command)\n    File "/opt/python/3.7.4/lib/python3.7/distutils/dist.py", line 985, in run_command\n      cmd_obj.run()\n    File "/opt/python/3.7.4/lib/python3.7/distutils/command/build.py", line 135, in run\n      self.run_command(cmd_name)\n    File "/opt/python/3.7.4/lib/python3.7/distutils/cmd.py", line 313, in run_command\n      self.distribution.run_command(command)\n    File "/opt/python/3.7.4/lib/python3.7/distutils/dist.py", line 985, in run_command\n      cmd_obj.run()\n    File "/tmp/pip-install-54da2nm6/fbprophet/setup.py", line 48, in run\n      build_models(target_dir)\n    File "/tmp/pip-install-54da2nm6/fbprophet/setup.py", line 36, in build_models\n      from fbprophet.models import StanBackendEnum\n    File "/tmp/pip-install-54da2nm6/fbprophet/fbprophet/__init__.py", line 8, in <module>\n      from fbprophet.forecaster import Prophet\n    File "/tmp/pip-install-54da2nm6/fbprophet/fbprophet/forecaster.py", line 14, in <module>\n      import numpy as np\n  ModuleNotFoundError: No module named 'numpy'\n  ----------------------------------------\n  ERROR: Failed building wheel for fbprophet\n    ERROR: Command errored out with exit status 1:\n     command: /opt/python/3.7.4/bin/python3.7 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-54da2nm6/fbprophet/setup.py'"'"'; __file__='"'"'/tmp/pip-install-54da2nm6/fbprophet/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-84z_vu2a/install-record.txt --single-version-externally-managed --compile --home=/tmp/pip-target-bwnaouac\n         cwd: /tmp/pip-install-54da2nm6/fbprophet/\n    Complete output (42 lines):\n    running install\n    running build\n    running build_py\n    creating build\n    creating build/lib\n    creating build/lib/fbprophet\n    creating build/lib/fbprophet/stan_model\n    Traceback (most recent call last):\n      File "<string>", line 1, in <module>\n      File "/tmp/pip-install-54da2nm6/fbprophet/setup.py", line 148, in <module>\n        """\n      File "/opt/python/3.7.4/lib/python3.7/site-packages/setuptools/__init__.py", line 145, in setup\n        return distutils.core.setup(**attrs)\n      File "/opt/python/3.7.4/lib/python3.7/distutils/core.py", line 148, in setup\n        dist.run_commands()\n      File "/opt/python/3.7.4/lib/python3.7/distutils/dist.py", line 966, in run_commands\n        self.run_command(cmd)\n      File "/opt/python/3.7.4/lib/python3.7/distutils/dist.py", line 985, in run_command\n        cmd_obj.run()\n      File "/opt/python/3.7.4/lib/python3.7/site-packages/setuptools/command/install.py", line 61, in run\n        return orig.install.run(self)\n      File "/opt/python/3.7.4/lib/python3.7/distutils/command/install.py", line 545, in run\n        self.run_command('build')\n      File "/opt/python/3.7.4/lib/python3.7/distutils/cmd.py", line 313, in run_command\n        self.distribution.run_command(command)\n      File "/opt/python/3.7.4/lib/python3.7/distutils/dist.py", line 985, in run_command\n        cmd_obj.run()\n      File "/opt/python/3.7.4/lib/python3.7/distutils/command/build.py", line 135, in run\n        self.run_command(cmd_name)\n      File "/opt/python/3.7.4/lib/python3.7/distutils/cmd.py", line 313, in run_command\n        self.distribution.run_command(command)\n      File "/opt/python/3.7.4/lib/python3.7/distutils/dist.py", line 985, in run_command\n        cmd_obj.run()\n      File "/tmp/pip-install-54da2nm6/fbprophet/setup.py", line 48, in run\n        build_models(target_dir)\n      File "/tmp/pip-install-54da2nm6/fbprophet/setup.py", line 36, in build_models\n        from fbprophet.models import StanBackendEnum\n      File "/tmp/pip-install-54da2nm6/fbprophet/fbprophet/__init__.py", line 8, in <module>\n        from fbprophet.forecaster import Prophet\n      File "/tmp/pip-install-54da2nm6/fbprophet/fbprophet/forecaster.py", line 14, in <module>\n        import numpy as np\n    ModuleNotFoundError: No module named 'numpy'\n    ----------------------------------------\nERROR: Command errored out with exit status 1: /opt/python/3.7.4/bin/python3.7 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-54da2nm6/fbprophet/setup.py'"'"'; __file__='"'"'/tmp/pip-install-54da2nm6/fbprophet/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-84z_vu2a/install-record.txt --single-version-externally-managed --compile --home=/tmp/pip-target-bwnaouac Check the logs for full command output.\nWARNING: You are using pip version 19.2.3, however version 20.0.2 is available.\nYou should consider upgrading via the 'pip install --upgrade pip' command.\n/opt/Kudu/Scripts/starter.sh oryx build /tmp/zipdeploy/extracted -o /home/site/wwwroot --platform python --platform-version 3.7 -p packagedir=.python_packages/lib/site-packages
Remote build failed!
```

**Comment by QEDHamburg** [comment]
Any News?

**Comment by kichalla** [comment]
I found that this issue is not specific to Oryx but in general a problem with `prophet`.
FYI: https://github.com/facebook/prophet/issues/401

**Comment by kichalla** [comment]
Closing this issue as it is not related to Oryx as mentioned in my earlier comment. Feel free to re-open it with more details.
