### ISSUE TITLE
Oryx can't find antenv during startup

### ISSUE THREAD

**Issue by br0cky** [microsoft/Oryx#675]
Hi all,

deploying a flask app to app service via localgit and VS code.

Here is output of startup:

> 2020-07-09T12:15:07.309830141Z 
> 2020-07-09T12:15:07.309851942Z   _____                               
> 2020-07-09T12:15:07.309857142Z   /  _  \ __________ _________   ____  
> 2020-07-09T12:15:07.309861243Z  /  /_\  \___   /  |  \_  __ \_/ __ \ 
> 2020-07-09T12:15:07.309865443Z /    |    \/    /|  |  /|  | \/\  ___/ 
> 2020-07-09T12:15:07.309869543Z \____|__  /_____ \____/ |__|    \___  >
> 2020-07-09T12:15:07.309873743Z         \/      \/                  \/ 
> 2020-07-09T12:15:07.309877744Z 
> 2020-07-09T12:15:07.309881544Z A P P   S E R V I C E   O N   L I N U X
> 2020-07-09T12:15:07.309885344Z 
> 2020-07-09T12:15:07.309889144Z Documentation: http://aka.ms/webapp-linux
> 2020-07-09T12:15:07.309892945Z Python 3.7.7
> 2020-07-09T12:15:07.309896845Z Note: Any data outside '/home' is not persisted
> 2020-07-09T12:15:07.339160825Z Starting OpenBSD Secure Shell server: sshd.
> 2020-07-09T12:15:07.346617754Z Site's appCommandLine: startup.sh
> 2020-07-09T12:15:07.346643155Z Checking of startup.sh is a file
> 2020-07-09T12:15:07.349176901Z App command line is a file on disk
> 2020-07-09T12:15:07.352866913Z App command line is a shell script, will execute this script as startup script
> 2020-07-09T12:15:07.356373314Z Launching oryx with: create-script -appPath /home/site/wwwroot -output /opt/startup/startup.sh -virtualEnvName antenv -defaultApp /opt/defaultsite -bindPort 8000 -userStartupCommand startup.sh
> 2020-07-09T12:15:07.361004980Z Cound not find build manifest file at '/home/site/wwwroot/oryx-manifest.toml'
> 2020-07-09T12:15:07.361019681Z Could not find operation ID in manifest. Generating an operation id...
> 2020-07-09T12:15:07.361111486Z Build Operation ID: d1131589-bf15-45b8-a48a-9d6e768b7371
> 2020-07-09T12:15:08.013049630Z Oryx Version: 0.2.20200522.2, Commit: bf724c0e83f3da74487f55cd304c63331dab7067, ReleaseTagName: 20200522.2
> 2020-07-09T12:15:08.311142250Z Writing output script to '/opt/startup/startup.sh'
> 2020-07-09T12:15:08.918030706Z WARNING: Could not find virtual environment directory /home/site/wwwroot/antenv.
> 2020-07-09T12:15:08.918065108Z WARNING: Could not find package directory /home/site/wwwroot/__oryx_packages__.
> 2020-07-09T12:15:09.156926527Z [2020-07-09 12:15:09 +0000] [46] [INFO] Starting gunicorn 20.0.4
> 2020-07-09T12:15:09.157322250Z [2020-07-09 12:15:09 +0000] [46] [INFO] Listening at: http://0.0.0.0:8000 (46)
> 2020-07-09T12:15:09.157367453Z [2020-07-09 12:15:09 +0000] [46] [INFO] Using worker: sync
> 2020-07-09T12:15:09.161251576Z [2020-07-09 12:15:09 +0000] [49] [INFO] Booting worker with pid: 49
> 2020-07-09T12:15:09.291566960Z [2020-07-09 12:15:09 +0000] [49] [ERROR] Exception in worker process
> 2020-07-09T12:15:09.291650565Z Traceback (most recent call last):
> 2020-07-09T12:15:09.291658565Z   File "/opt/python/3.7.7/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
> 2020-07-09T12:15:09.291676667Z     worker.init_process()
> 2020-07-09T12:15:09.291683067Z   File "/opt/python/3.7.7/lib/python3.7/site-packages/gunicorn/workers/base.py", line 119, in init_process
> 2020-07-09T12:15:09.291688767Z     self.load_wsgi()
> 2020-07-09T12:15:09.291694168Z   File "/opt/python/3.7.7/lib/python3.7/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
> 2020-07-09T12:15:09.291699768Z     self.wsgi = self.app.wsgi()
> 2020-07-09T12:15:09.291705168Z   File "/opt/python/3.7.7/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
> 2020-07-09T12:15:09.291711769Z     self.callable = self.load()
> 2020-07-09T12:15:09.291716969Z   File "/opt/python/3.7.7/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
> 2020-07-09T12:15:09.291722569Z     return self.load_wsgiapp()
> 2020-07-09T12:15:09.291729670Z   File "/opt/python/3.7.7/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
> 2020-07-09T12:15:09.291735270Z     return util.import_app(self.app_uri)
> 2020-07-09T12:15:09.291740970Z   File "/opt/python/3.7.7/lib/python3.7/site-packages/gunicorn/util.py", line 358, in import_app
> 2020-07-09T12:15:09.291746871Z     mod = importlib.import_module(module)
> 2020-07-09T12:15:09.291752171Z   File "/opt/python/3.7.7/lib/python3.7/importlib/__init__.py", line 127, in import_module
> 2020-07-09T12:15:09.291757671Z     return _bootstrap._gcd_import(name[level:], package, level)
> 2020-07-09T12:15:09.291763171Z   File "", line 1006, in _gcd_import
> 2020-07-09T12:15:09.291769572Z   File "", line 983, in _find_and_load
> 2020-07-09T12:15:09.291774972Z   File "", line 967, in _find_and_load_unlocked
> 2020-07-09T12:15:09.291780372Z   File "", line 677, in _load_unlocked
> 2020-07-09T12:15:09.291785773Z   File "", line 728, in exec_module
> 2020-07-09T12:15:09.291791173Z   File "", line 219, in _call_with_frames_removed
> 2020-07-09T12:15:09.291796673Z   File "/home/site/wwwroot/libs.py", line 3, in 
> 2020-07-09T12:15:09.291802274Z     from app import create_app, db
> 2020-07-09T12:15:09.291807374Z   File "/home/site/wwwroot/app/__init__.py", line 3, in 
> 2020-07-09T12:15:09.291812874Z     from flask_sqlalchemy import SQLAlchemy
> 2020-07-09T12:15:09.291818175Z ModuleNotFoundError: No module named 'flask_sqlalchemy'
> 2020-07-09T12:15:09.291823675Z [2020-07-09 12:15:09 +0000] [49] [INFO] Worker exiting (pid: 49)
> 2020-07-09T12:15:09.322545839Z [2020-07-09 12:15:09 +0000] [46] [INFO] Shutting down: Master
> 2020-07-09T12:15:09.322581341Z [2020-07-09 12:15:09 +0000] [46] [INFO] Reason: Worker failed to boot.

antenv folder doesn't exist in /home/site/wwwroot hence error but i noticed there is /antenv which contains all dependencies from my requirements.txt so why does it end up there? Also during deployment logs i notice antenv gets created and dependencies are installed, then the antenv is compressed.

Thanks

**Comment by br0cky** [comment]
Closing as i think it was something i messed up during deployment
