### ISSUE TITLE
Build is not including Microsoft.EntityFrameworkCore Version=5.0.1.0

### ISSUE THREAD

**Issue by JaredMRomano** [microsoft/Oryx#893]
### Bug Report

I just updated all my nuget packages of my project to 5.0.1. When using local git to deploy to a linux web server set to .NET 5,  I pushed successfully to my site and it reports "Deployment successful " in the output window.  However when the service goes to start I get the following message.

Unhandled exception. System.IO.FileLoadException: Could not load file or assembly 'Microsoft.EntityFrameworkCore, Version=5.0.1.0

I am assuming the dependency is getting found as a NuGet package since it is not throwing any package reference errors, but not getting included in the build.

- At what date and time did you most recently experience the problem?

2020-12-15T14:09:27.697529196Z

- Where did you experience the problem? E.g. Azure Web Apps, Azure Functions, Azure Container Registry, or offline use.

Azure Web Apps

- What did you expect or want to happen?
The app to be deployed and correctly built by Oryx with all the packages

- How can we reproduce it?
Update an existing project to EF core 5.0.1 and deploy the project

- Do you have log output? Please include between the backticks:

```
2020-12-15T14:09:10.071Z INFO  - 5.0_20200918.1 Pulling from appsvc/dotnetcore
2020-12-15T14:09:10.072Z INFO  -  Digest: sha256:b9bdeb174703f60016a9e2632c44a402e29be28c1885ae281a22ea4ce66d01d6
2020-12-15T14:09:10.078Z INFO  -  Status: Image is up to date for 10.0.5.148:13209/appsvc/dotnetcore:5.0_20200918.1
2020-12-15T14:09:10.091Z INFO  - Pull Image successful, Time taken: 0 Minutes and 1 Seconds
2020-12-15T14:09:10.192Z INFO  - Starting container for site
2020-12-15T14:09:10.193Z INFO  - docker run -d -p 7668:8080 --name <sitename>__fe3c_0_732484c8 -e WEBSITE_SITE_NAME=<sitename> -e WEBSITE_AUTH_ENABLED=False -e WEBSITE_ROLE_INSTANCE_ID=0 -e WEBSITE_HOSTNAME=<sitename>-staging.azurewebsites.net -e WEBSITE_INSTANCE_ID=7b65e78aa202bf281b88a5638721aa4f837c46d0fd75afabdef0cb2870a44461 appsvc/dotnetcore:5.0_20200918.1 dotnet <projectname>.dll
2020-12-15T14:09:10.194Z INFO  - Logging is not enabled for this container.Please use https://aka.ms/linux-diagnostics to enable logging to see container logs here.
2020-12-15T14:09:19.000Z INFO  - Initiating warmup request to container <sitename>__fe3c_0_732484c8 for site <sitename>__fe3c
/home/LogFiles/kudu/deployment/18b62c7dbaaf-6f566e3b-6e61-415f-bd95-e2ae57c6da66.txt  (https://<sitename>-staging.scm.azurewebsites.net/api/vfs/LogFiles/kudu/deployment/18b62c7dbaaf-6f566e3b-6e61-415f-bd95-e2ae57c6da66.txt)
2020-12-15T00:33:55      <projectname> -> /home/site/wwwroot/
2020-12-15T00:33:58
2020-12-15T00:33:58    Removing existing manifest file
2020-12-15T00:33:59    Creating a manifest file...
2020-12-15T00:33:59    Manifest file created.
2020-12-15T00:33:59
2020-12-15T00:33:59    Done in 701 sec(s).
2020-12-15T00:34:03  Running post deployment command(s)...
2020-12-15T00:34:03  Triggering recycle (preview mode disabled).
2020-12-15T00:34:04  Deployment successful.
Ending Log Tail of existing logs ---
Starting Live Log Stream ---
2020-12-15T14:09:18.000297910Z   _____
2020-12-15T14:09:18.000338010Z   /  _  \ __________ _________   ____
2020-12-15T14:09:18.000346110Z  /  /_\  \___   /  |  \_  __ \_/ __ \
2020-12-15T14:09:18.000352910Z /    |    \/    /|  |  /|  | \/\  ___/
2020-12-15T14:09:18.000359310Z \____|__  /_____ \____/ |__|    \___  >
2020-12-15T14:09:18.000509011Z         \/      \/                  \/
2020-12-15T14:09:18.000518411Z A P P   S E R V I C E   O N   L I N U X
2020-12-15T14:09:18.000524411Z
2020-12-15T14:09:18.000530011Z Documentation: http://aka.ms/webapp-linux
2020-12-15T14:09:18.000535811Z Dotnet quickstart: https://aka.ms/dotnet-qs
2020-12-15T14:09:18.000541611Z ASP .NETCore Version: 5.0.0
2020-12-15T14:09:18.000547511Z Note: Any data outside '/home' is not persisted
2020-12-15T14:09:19.037314131Z Running oryx create-script -appPath /home/site/wwwroot -output /opt/startup/startup.sh -defaultAppFilePath /defaulthome/hostingstart/hostingstart.dll     -bindPort 8080 -userStartupCommand 'dotnet <projectname>.dll'
2020-12-15T14:09:19.745031963Z Found build manifest file at '/home/site/wwwroot/oryx-manifest.toml'. Deserializing it...
2020-12-15T14:09:19.748725590Z Build Operation ID: |sYeZ5H5mYEc=.45a902a7_
2020-12-15T14:09:22.123523514Z Writing output script to '/opt/startup/startup.sh'
2020-12-15T14:09:22.845681551Z Running user provided startup command...
2020-12-15T14:09:27.697497096Z Unhandled exception. System.IO.FileLoadException: Could not load file or assembly 'Microsoft.EntityFrameworkCore, Version=5.0.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The located assembly's manifest definition does not match the assembly reference. (0x80131040)
2020-12-15T14:09:27.697529196Z File name: 'Microsoft.EntityFrameworkCore, Version=5.0.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
2020-12-15T14:09:27.697535396Z    at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
2020-12-15T14:09:27.697539696Z    at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
2020-12-15T14:09:27.697544096Z    at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.InvokeCore(Object instance, IServiceCollection services)
2020-12-15T14:09:27.697548196Z    at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass9_0.<Invoke>g__Startup|0(IServiceCollection serviceCollection)
2020-12-15T14:09:27.697553096Z    at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.Invoke(Object instance, IServiceCollection services)
2020-12-15T14:09:27.697557196Z    at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass8_0.<Build>b__0(IServiceCollection services)
2020-12-15T14:09:27.697561597Z    at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.UseStartup(Type startupType, HostBuilderContext context, IServiceCollection services, Object instance)
2020-12-15T14:09:27.697572597Z    at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass13_0.<UseStartup>b__0(HostBuilderContext context, IServiceCollection services)
2020-12-15T14:09:27.697586897Z    at Microsoft.Extensions.Hosting.HostBuilder.CreateServiceProvider()
2020-12-15T14:09:27.697590697Z    at Microsoft.Extensions.Hosting.HostBuilder.Build()
2020-12-15T14:09:27.707122964Z    at <projectname>.Program.Main(String[] args) in /tmp/8d8a08f71d552a7/<projectname>/Server/Program.cs:line 40
2020-12-15T14:09:28.201844743Z Gathering state for process 27 dotnet
2020-12-15T14:09:29.308297023Z /opt/startup/startup.sh: line 10:    27 Aborted                 (core dumped) dotnet <projectname>.dll
2020-12-15T14:09:31.439Z ERROR - Container <sitename>__fe3c_0_732484c8 for site <sitename>__fe3c has exited, failing site start
2020-12-15T14:09:31.477Z ERROR - Container <sitename>__fe3c_0_732484c8 didn't respond to HTTP pings on port: 8080, failing site start. See container logs for debugging.
2020-12-15T14:09:31.651Z INFO  - Stopping site <sitename>__fe3c because it failed during startup.
```

**Comment by arroyc** [comment]
Thanks for reporting this issue ... I'm sorry for your trouble .. would you be able to provide a sample app so that we can try to repro this and a possible fix may be?

**Comment by JaredMRomano** [comment]
Unfortunately not any more.  What I ended up doing was creating a new deployment slot, deploying to the new slot and swapping. It seems to be the standard solution for me when the container fails to boot.  I have found, I usually have to do it if I have updated nuget packages.  I assume things are not getting purged correctly between deployments. Hopefully that helps.

**Comment by arroyc** [comment]
thanks @JaredMRomano for reporting ... we will keep an  eye on this ... please feel free to report any other issues ... at this moment I'm closing this issue here
